### ISSUE TITLE
[feat] Display the owner of selected pixel

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#10]
When selecting a pixel on the canvas, load the account that placed the pixel into the `Owner` field ( Replace the hardcoded `placed_by` value ). This data is stored in the `Pixels` table from Postgres.

I had part of this working, but since refactoring, this needs to be fixed. ( See references for details )

#### References
- [Owner field in frontend](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/frontend/src/canvas/SelectedPixelPanel.js#L9)
- [Backend route for pixel info](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/backend/routes/pixel.go#L43)
- [Frontend pixel select logic](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/frontend/src/canvas/Canvas.js#L171)

**Comment by Ayoazeez26** [comment]
@b-j-roberts I would like to be assigned to this

**Comment by Ayoazeez26** [comment]
@b-j-roberts in the `Canvas.js` file, this api call currently returns a string value with a bunch of 0s which was set in the api call shown in the second screenshot. My question is, would this returned address value be what I would set in the `placed_by` field?

![Screenshot 2024-04-12 at 07 49 52](https://github.com/keep-starknet-strange/art-peace/assets/44169294/100ce6f4-43ad-4c32-8eaf-e35b9ac789cd)




![Screenshot 2024-04-12 at 07 47 19](https://github.com/keep-starknet-strange/art-peace/assets/44169294/427bcfb1-87ea-4849-a6f0-f5af09226899)
