### ISSUE TITLE
[feat] Highlight hovered extra pixel

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#100]
Currently, when placing extra pixels, an extra-pixel panel will appear on the right. You can click an extra pixel in the panel to delete it from the canvas. 

This issue is to move the selected pixel indicator/highlighter to the extra pixel being hovered in the extra pixel panel so the user can more easily see which pixel they are about to remove.

#### References
- [Extra pixels panel](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/canvas/ExtraPixelsPanel.js#L63)
- [Pixel selector](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/App.js#L132)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @kateberryd 

Please comment here so I can assign you, if you're still interested.

**Comment by kateberryd** [comment]
Yes, I am interested. Thank you
