### ISSUE TITLE
[feat] Extra pixels eraser

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#101]
When placing extra pixels on the canvas, if the user makes a mistake, the only way to remove a pixel added is to use the extra pixel panel, find the exact pixel to remove, and click it.

A more user-friendly way would be to create an eraser tool that can remove extra pixels from the canvas. It would be cool to allow holding down to erase all extra pixels you go over or clicking to remove a single extra pixel.

#### References
- [Eraser mode activate](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/canvas/ExtraPixelsPanel.js#L15)
- [Extra pixels metadata](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/App.js#L106)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @EjembiEmmanuel 

Please comment here so I can assign you, if you're still interested.

**Comment by EjembiEmmanuel** [comment]
@b-j-roberts yes, I'm still interested.
