### ISSUE TITLE
[feat] Username edit cancel button

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#102]
When a username has been set, but the user clicks to edit their username, it would be nice to be able to cancel the edit without changing tabs. Add a cancel button to the username form to stop edit.

#### References
- [Username form](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/account/Account.js#L104)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @Joy-adah

Please comment here so I can assign you, if you're still interested.

**Comment by Joy-Adah** [comment]
Hi @b-j-roberts yes, I am.
