### ISSUE TITLE
[feat] Quest: NFT mint quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#104]
Create a quest for minting an NFT. Have the quest take the nft's `token_id` as call data, and use a dispatcher on the `canvas_nft` contract to check that the NFT's metadata contains the user as `minter` on the corresponding NFT metadata.

Also create corresponding tests.

#### References
- [NFT Metadata](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/onchain/src/nfts/interfaces.cairo#L15)
- [NFT store to dispatch](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/onchain/src/nfts/interfaces.cairo#L19)
- [Example Quest](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/template_quest.cairo)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @mubarak23 

Please comment here so I can assign you, if you're still interested.

**Comment by TAdev0** [comment]
Hey @b-j-roberts  is it up for grab or not?

**Comment by mubarak23** [comment]
Yes, kindly assign it to me 

thank you

**Comment by b-j-roberts** [comment]
> Hey @b-j-roberts is it up for grab or not?

@TAdev0 Mubarak had already expressed interest in this task, I pinged you on another similar issue if you'd like it instead.

**Comment by TAdev0** [comment]
sure, i didnt see any comment before your first one, i thought you commented the wrong issue. Sorry.

**Comment by mubarak23** [comment]
my nftQuest is going to implement IQuest trait  right @b-j-roberts
