### ISSUE TITLE
[dev] Use async / await

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#108]
This issue is to refactor our current `fetch` calls on the frontend to make them use ES6 async/await syntax. Please change all fetch calls to work with async await by using the api service component.

#### References
- [api service component](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/services/apiService.js#L5)
- [Example of call to change](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/App.js#L112)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @Immanuelolivia1

Please comment here so I can assign you, if you're still interested.

**Comment by Immanuelolivia1** [comment]
I'm still interested in the issue @b-j-roberts

**Comment by kenkomu** [comment]
@b-j-roberts can I work on this?
