### ISSUE TITLE
[feat] Load color votes from Postgres

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#11]
On the `Voting` component, load the colors and vote counts from Postgres on init. Sort them by vote count.

This includes creating a backend route to query the colors from Postgres and requesting this route on the frontend component.

#### References
[Frontend voting component](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/frontend/src/tabs/Voting.js#L6)
[Postgres DB](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/postgres/init.sql#L70)
[Backend routes](https://github.com/keep-starknet-strange/art-peace/tree/f62a06ef0fcea5a810a9d380d974f7106c76b56a/backend/routes)

**Comment by faytey** [comment]
i'd love to work on this if available

**Comment by b-j-roberts** [comment]
Awesome, I'll assign you @faytey . Welcome to the project!

**Comment by b-j-roberts** [comment]
Hey @faytey , are you actively working on this? I'd like to free it up for someone to take, if not. I'll add more issues in the future, which you can if you haven't had time for this.

**Comment by faytey** [comment]
Yes sorry I started yesterday but haven’t gone far, you can free it up for the other contributor, I’d wait when you add more issues. Thanks

**Comment by addegbenga** [comment]
I will like to work on this

**Comment by fishonamos** [comment]
@b-j-roberts I will love to work on this since it is similar to what I did for daily and main quests.

**Comment by b-j-roberts** [comment]
@addegbenga Sorry for the late reply, I'll assign you now if you are still free for the issue.

**Comment by b-j-roberts** [comment]
@faytey No worries, thank you for the update!

**Comment by addegbenga** [comment]
> @addegbenga Sorry for the late reply, I'll assign you now if you are still free for the issue.

Yeah, i am still availaible to work on it.
