### ISSUE TITLE
[feat] Track time left in day

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#12]
There will be a new color vote each day & new quests each day.

Given a start time ( say 15:00 UTC for testing ), dynamically calculate the `timeLeftInDay` (the time left until 15:00 UTC the next day ). Create the `timeLeftInDay` state variable on the app that can be passed as a prop to the `Voting` and `Quests` modules. Set the `timeLeftInDay` variable as a human-readable string time like `hh:mm:ss`.

( Don't use the hardcoded time-interval based `useEffect` like in the `Voting` component. Calculate the `timeLeftInDay` more accurately each loop like in the `PixelSelector` component. )

#### References
[App component](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/frontend/src/App.js)
[PixelSelector component](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/frontend/src/canvas/PixelSelector.js#L21)

**Comment by raizo07** [comment]
Hello @b-j-roberts I'll like to be assigned to this.

**Comment by b-j-roberts** [comment]
I'm unassigning this for now, @raizo07 , while you work on finishing your other PR.

**Comment by Ayoazeez26** [comment]
I would like to work on this
