### ISSUE TITLE
[feat] Get user vote route

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#128]
This issue involves creating and using a route to get the color a user voted for. Use the `address` as a query parameter for the route.

The color vote data is stored in Postgres, so the backend must query the data from there. The frontend will call this route within the voting component. If the user has no vote in the table, return '0' to indicate no vote was made yet.

Use the apiService fetchWrapper to make the call on the frontend side.

#### References
- [ApiService](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/frontend/src/services/apiService.js#L5)
- [Api query example](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/frontend/src/tabs/voting/Voting.js#L35)
- [Color vote table](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/postgres/init.sql#L97)
- [Voting component](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/frontend/src/tabs/voting/Voting.js#L11)
- [Backend route example](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/backend/routes/user.go#L34)

**Comment by Immanuelolivia1** [comment]
Can I be assigned to this ??

**Comment by Ayoazeez26** [comment]
Can I work on this?
