### ISSUE TITLE
[feat] Quest: Rainbow Quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#129]
Create a quest that will be claimable if the user has placed at least one pixel of each color in the color palette. The check can be done over all days.

Create corresponding tests.

#### References
- [Example quest](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/pixel_quest.cairo)
- [Color palette info](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/onchain/src/art_peace.cairo#L30)
- [User pixel data](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/onchain/src/art_peace.cairo#L51)

**Comment by b-j-roberts** [comment]
For sure! Glad to have you on the issue! @TAdev0

**Comment by TAdev0** [comment]
thanks @b-j-roberts  !
