### ISSUE TITLE
[feat] Load quests & statuses from Postgres

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#13]
On the `Quests` component, load the quests and statuses from Postgres on init. Sort them by completion ( completed quests go on the bottom )

This includes creating a backend route to query the quests from Postgres and requesting this route on the frontend component.

#### References
[Frontend quests component](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/tabs/quests/Quests.js)
[Postgres DB](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/postgres/init.sql#L44)
[Backend routes](https://github.com/keep-starknet-strange/art-peace/tree/f62a06ef0fcea5a810a9d380d974f7106c76b56a/backend/routes)

**Comment by fishonamos** [comment]
Hi @b-j-roberts . Can this be assigned to me?

**Comment by b-j-roberts** [comment]
Definitely @fishonamos , let me know if you have any questions. Welcome to the project!
