### ISSUE TITLE
[feat] Quest: Username quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#130]
Create a quest that is claimable if the user has claimed a username.

Create corresponding tests.

#### References
- [Example Quest](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/template_quest.cairo)
- [Username store](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/username_store/username_store.cairo)

**Comment by fishonamos** [comment]
hi

**Comment by Calebux** [comment]
Hi @b-j-roberts i'll like to work on this

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by b-j-roberts** [comment]
Definitely @Calebux , let me know if you have any questions.

**Comment by b-j-roberts** [comment]
For this issue, you can use this new field to check if a user has a username : 
https://github.com/keep-starknet-strange/art-peace/blob/294e956d821978aa9e4a62a4ebd51c77134f8dd5/onchain/src/username_store/username_store.cairo#L16

by calling this function : https://github.com/keep-starknet-strange/art-peace/blob/294e956d821978aa9e4a62a4ebd51c77134f8dd5/onchain/src/username_store/username_store.cairo#L87 and checking if it is 0 or not

**Comment by b-j-roberts** [comment]
@Calebux  Have you started working on this? If so, could you create a draft PR of your work so far?
Otherwise, I'd like to assign this to someone available to work on it.

**Comment by Calebux** [comment]
@b-j-roberts i have, i'd be sending a PR soon
