### ISSUE TITLE
[feat] Quest: Vote Quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#131]
Create a quest to check if a user has voted for a new color to add to the color palette. This will be a daily quest, so have the dayIdx be taken as a constructor argument and store to use in the `is_claimable` function.

Create corresponding tests.

#### References

- [Example Quest](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/template_quest.cairo)
- [Vote metadata](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/onchain/src/art_peace.cairo#L37)

**Comment by Calebux** [comment]
i want to

**Comment by princeibs** [comment]
Can I hop on this? @b-j-roberts

**Comment by b-j-roberts** [comment]
Definitely @princeibs, good luck! Let me know if you have questions.

**Comment by b-j-roberts** [comment]
@princeibs Have you started working on this? If so, could you create a draft PR of your work so far?
Otherwise, I'd like to assign this to someone available to work on it.

**Comment by princeibs** [comment]
Just to confirm, will I include tests for this feature?
@b-j-roberts

**Comment by b-j-roberts** [comment]
@princeibs Can you please submit a PR of what you have done so far, even if its not done? I'd like to get this moving.

**Comment by princeibs** [comment]
I will push my progress on the pr ASAP

**Comment by b-j-roberts** [comment]
If anyone else is willing to help implement this, feel free to submit PRs / work here.

**Comment by princeibs** [comment]
Quest implementation completed, tests is in progress. Kindly check out the draft pr @b-j-roberts

**Comment by princeibs** [comment]
test is completed. pr ready for review
