### ISSUE TITLE
[feat] Quest: Hodl quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#132]
Create a quest that will be claimable if a user holds `X` extra pixels. Take the value for `X` as a variable in the constructor.

#### References

- [Example Quest](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/template_quest.cairo)
- [Extra pixels metadata](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/onchain/src/art_peace.cairo#L29)

**Comment by raizo07** [comment]
Hello @b-j-roberts kindly assign me to this.

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by b-j-roberts** [comment]
I'll assign you @mubarak23 , since I think your other issue is mostly done.

**Comment by mubarak23** [comment]
@b-j-roberts thank you
