### ISSUE TITLE
[dev] Design improvement document

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#133]
Create a design improvement document that can be used as a reference for improving the UI/UX of the art/peace app.

It is probably best to create a Google doc or similar that can be shared and commented on by anyone.

**Comment by b-j-roberts** [comment]
@UmarSalihu If you could comment here, I can assign you.
Thank you!

**Comment by UmarSalihu** [comment]
Hi @b-j-roberts . Please go ahead.
Thanks.

**Comment by kenkomu** [comment]
Can I work on this?

**Comment by UmarSalihu** [comment]
Hey @b-j-roberts , here's my deliverable for the task
https://docs.google.com/document/d/1X1ZJmbG0o-crm8bBSKl3eI-pOLjhb7FLA9OOnTyZoq8/edit?usp=sharing

Kindly review.
Thanks

**Comment by b-j-roberts** [comment]
Can you give me access to comment on the document?

**Comment by UmarSalihu** [comment]
@b-j-roberts Yeah, i can do that.
Drop your email, and I'll give you editing access.

You can send the email over on Telegram if you want.

**Comment by b-j-roberts** [comment]
@UmarSalihu I left some comments on the doc, if you could check them out

**Comment by UmarSalihu** [comment]
@b-j-roberts I just responded to the comments you added. Kindly check them out.
Thanks
