### ISSUE TITLE
[feat] Rank icon setup

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#134]
Displaying an icon for each rank in the `Accounts` tab on the frontend would be cool.

This issue is to add the display functionality for the rank icon. The icon and the rank name will both be set to a specific color for each rank and controlled through CSS styling.

You won't need to create the icons, since the ranks aren't finalized. So you can just use a dummy icon for now to get the logic working.

#### References
- [Accounts tab](https://github.com/keep-starknet-strange/art-peace/blob/b330eece8d98a10e4bea128047c552f3e5d0910d/frontend/src/tabs/account/Account.js#L127)

**Comment by Ayoazeez26** [comment]
@b-j-roberts Thank you for having me.
