### ISSUE TITLE
[feat] Onchain color voting

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#14]
Each day, there will be a vote to add more colors to the palette. Create functionality on the `ArtPeace` contract for users to vote. Use a map to store the users who voted today to prevent double voting. ( Key should be 2 values (dayIdx, user); value should be boolean for if voted )

Emit an event from the vote onchain.

Create an internal function ( not directly callable externally ) for settling the color vote, which will add the top X colors ( hardcoded to 3 for now ) to the color palette.

#### References
[ArtPeace Contract](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/art_peace.cairo)

**Comment by AkankshaAttavar** [comment]
@b-j-roberts can you please assign this to me, Thank you.

**Comment by b-j-roberts** [comment]
For sure, welcome to the project @AkankshaAttavar !

**Comment by ptisserand** [comment]
Hi @b-j-roberts , can I work on this one ? 
Do you think it's only to finalize #56 ?

**Comment by b-j-roberts** [comment]
Yeah, I can assign you @ptisserand 

The description here isn't really accurate anymore. I setup the onchain voting already, but the finalize functionality is still missing : https://github.com/keep-starknet-strange/art-peace/blob/f83f71a4e4ffa62826404c95697f2bffb990937d/onchain/src/art_peace.cairo#L318

Do you think you could figure out what to do there? Or would you need more instruction?

**Comment by ptisserand** [comment]
Hi @b-j-roberts, I need more instruction: how the next day's votable colors should be chosen ?

**Comment by b-j-roberts** [comment]
> Hi @b-j-roberts, I need more instruction: how the next day's votable colors should be chosen ?

The next day's votable colors will be those left over from the previous day that didn't get added to the palette.

**Comment by ptisserand** [comment]
Hi @b-j-roberts, I think I have to modify `votable_colors_count` to be a `LegacyMap<u32,u8>` to be able to iterate on `votable_colors` when day is not the current one:
https://github.com/keep-starknet-strange/art-peace/blob/ab4d22fd3e7dacbd6938b44ed6fd21ba8f64c49c/onchain/src/art_peace.cairo#L33-L35

What do you think ?

**Comment by ptisserand** [comment]
Hum with the following assert:
https://github.com/keep-starknet-strange/art-peace/blob/ab4d22fd3e7dacbd6938b44ed6fd21ba8f64c49c/onchain/src/art_peace.cairo#L320

it's impossible to vote for the first color of `votable_colors` 

I think we should remove this assert and updating the out of bounds with:
```
assert(color < self.votable_colors_count.read(), 'Color out of bounds');
```

@b-j-roberts is it ok for you ?

**Comment by b-j-roberts** [comment]
> Hi @b-j-roberts, I think I have to modify `votable_colors_count` to be a `LegacyMap<u32,u8>` to be able to iterate on `votable_colors` when day is not the current one:
> 
> https://github.com/keep-starknet-strange/art-peace/blob/ab4d22fd3e7dacbd6938b44ed6fd21ba8f64c49c/onchain/src/art_peace.cairo#L33-L35
> 
> What do you think ?

Sure, that change should be fine to make

**Comment by b-j-roberts** [comment]
> Hum with the following assert:
> 
> https://github.com/keep-starknet-strange/art-peace/blob/ab4d22fd3e7dacbd6938b44ed6fd21ba8f64c49c/onchain/src/art_peace.cairo#L320
> 
> it's impossible to vote for the first color of `votable_colors`
> 
> I think we should remove this assert and updating the out of bounds with:
> 
> ```
> assert(color < self.votable_colors_count.read(), 'Color out of bounds');
> ```
> 
> @b-j-roberts is it ok for you ?

The 0 position indicates no vote, so there shouldn't be any votable colors at position 0. This is because `user_votes` will be 0 by default.

**Comment by ptisserand** [comment]
> 
> The 0 position indicates no vote, so there shouldn't be any votable colors at position 0. This is because `user_votes` will be 0 by default.

Ok it's clear, I have updated my PR to handle index of votable colors start at 1.
