### ISSUE TITLE
[dev] Refactor quests assertions and events

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#140]
There is some refactoring I would like to do on the quests:

1. I'd like to move QuestClaimed events from within the quest contracts to the ArtPeace contract, it will make it easier to index
2. Some quests use assert! on failed claim, others return 0 reward. I'd like to move all of them to assert! calls

**Comment by b-j-roberts** [comment]
Thanks @TAdev0 for taking on this issue, comment here and I can assign you!

**Comment by TAdev0** [comment]
@b-j-roberts  oh we are synchronous i just created an issue :p
will delete it
