### ISSUE TITLE
[feat] Template image size & hash check

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#148]
We would like to check that the template image passed into the `complete_template` function matches the template image size & hash stored onchain.

There is already a `compute_template_hash` function defined here : https://github.com/keep-starknet-strange/art-peace/blob/294e956d821978aa9e4a62a4ebd51c77134f8dd5/onchain/src/tests/art_peace.cairo#L157

It will need to be moved to the `ITemplateVerifier` trait and used within the `complete_template` function to verify the image data.

Also, for the size check, you can check that the templates width * height == template image length

#### References
- [Complete Template Function](https://github.com/keep-starknet-strange/art-peace/blob/294e956d821978aa9e4a62a4ebd51c77134f8dd5/onchain/src/tests/art_peace.cairo#L157)
- [Template checks in complete template](https://github.com/keep-starknet-strange/art-peace/blob/294e956d821978aa9e4a62a4ebd51c77134f8dd5/onchain/src/art_peace.cairo#L566)
- [Template  store component](https://github.com/keep-starknet-strange/art-peace/blob/294e956d821978aa9e4a62a4ebd51c77134f8dd5/onchain/src/templates/component.cairo#L12)
- [Template metadata](https://github.com/keep-starknet-strange/art-peace/blob/294e956d821978aa9e4a62a4ebd51c77134f8dd5/onchain/src/templates/interfaces.cairo#L4)

**Comment by b-j-roberts** [comment]
Thanks, @Nuelose, for volunteering for this issue! Comment here and I can assign you.

**Comment by NueloSE** [comment]
Hi @b-j-roberts kindly assign me

**Comment by b-j-roberts** [comment]
@NueloSE Any updates?
If you haven't had time that is fine, but I'd like to assign this to someone else if so. Please submit a draft PR of your work so far if you've started already.

**Comment by NueloSE** [comment]
good day @b-j-roberts sorry for the late respond.
I had an issue with the task compiling after implementing all the task.
I was waiting for the office hour this week to share my challenge.
By the way i made a draft PR as advised. 

kindly assist
