### ISSUE TITLE
[feat] Start a new day

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#15]
There are various things like color votes and quests, which reset each day.

Create a function on the `ArtPeace` contract to increase the `dayIdx` by 1 if enough time has passed for a day to be completed. Set the new start time for the next day & emit a `NewDay` event.

#### References
[ArtPeace Contract](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/art_peace.cairo)

**Comment by TAdev0** [comment]
Hi @b-j-roberts  may I be assigned to this issue?

**Comment by b-j-roberts** [comment]
Yeah, I'll assign you now @TAdev0 . Welcome to the project!

**Comment by TAdev0** [comment]
Will work on it tomorrow. Thanks !
