### ISSUE TITLE
[feat] Extra pixels placed event

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#16]
Add a `PlacedExtraPixel` event to the `place_extra_pixels` function on the `ArtPeace` contract to emit when extra pixels are placed.
Add an event listener to the Apibara indexer to listen for this event and update Postgres, respectively.

#### References
[place_extra_pixels func](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/onchain/src/art_peace.cairo#L181)
[Extra pixels table in Postgres](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/postgres/init.sql#L23)
[Placed Pixels table in Postgres](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/postgres/init.sql#L3)
[Indexer script](https://github.com/keep-starknet-strange/art-peace/blob/main/indexer/docker-script.js)

**Comment by tekkac** [comment]
Ahoy, can I take this?

**Comment by b-j-roberts** [comment]
For sure, let me know if you have any questions @tekkac .

**Comment by tekkac** [comment]
Should we emit:
- a. one event per pixel
- b. one event with a list of extra pixels?
 The naming hints at a, but just wanted to make sure.

**Comment by b-j-roberts** [comment]
> Should we emit:
> 
> * a. one event per pixel
> * b. one event with a list of extra pixels?
>   The naming hints at a., but the code comment hints at b.
>   Just wanted to make sure.

I think b would be the better option, sorry for the inconsistent description.
However, there should be multiple new rows added to the `PixelPlaced` table in Postgres after the event gets indexed.

**Comment by NueloSE** [comment]
Hi b-j-robets I would like to take on this if you are reassgning
