### ISSUE TITLE
[bug] Rapidly place multiple pixels

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#168]
**How to reproduce:**
After clicking "Place pixel" you can rapidly click on the canvas in 2 or more separate locations and place more than one pixel before the frontend stops you. This should not happen. After clicking once in "Place pixel" mode, you should not be able to click again until the timer runs down.

**Comment by Ayoazeez26** [comment]
Can I pick this up @b-j-roberts

**Comment by Jemiiah** [comment]
@b-j-roberts i would love to work on this issue

**Comment by Jemiiah** [comment]
@b-j-roberts 🚀🚀
