### ISSUE TITLE
[feat] Liking NFTs

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#169]
There is a button on the frontend to like an NFT in the "All NFTs" panel. These buttons need to be linked to the backend to like and unlike nfts.

#### References

- [Frontend like button](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/frontend/src/tabs/nfts/NFTItem.js#L19)
- [Backend like functions](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/backend/routes/nft.go#L18)

**Comment by fishonamos** [comment]
Let me hop on this @b-j-roberts

**Comment by raizo07** [comment]
@b-j-roberts I'll like to work on this

**Comment by rajiabdul** [comment]
I will love to hop on this
