### ISSUE TITLE
[feat] Onchain Usernames

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#17]
Create a username store onchain.

Create a mapping in storage for `felt252` usernames -> User address and a set of functions for users to claim and view usernames.

Also, create a function to allow people to transfer usernames. Only the username's owner should be able to transfer to another address.

Emit an event for `UserCreated` & `UserTransferred`.

Make this a separate Username store contract or create a component which the `ArtPeace` contract uses.

#### References
[Onchain directory](https://github.com/keep-starknet-strange/art-peace/tree/main/onchain)
[Cairo components](https://book.cairo-lang.org/ch16-02-02-component-dependencies.html?highlight=component#component-dependencies)

**Comment by mubarak23** [comment]
@b-j-roberts please i will like to work on this issue, kindly assign it to me

**Comment by b-j-roberts** [comment]
Will do @mubarak23 , thank you and welcome to the project !

**Comment by mubarak23** [comment]
thank you, for the username storage, aside storing the username address, as in  ```
struct Storage {
        username: LegacyMap::<ContractAddress, felt252>
    }
```
do we need to store any other data

**Comment by b-j-roberts** [comment]
> do we need to store any other data

On Starknet, I believe this would be the only data needed. I think we want usernames to be unique, so having the mapping be like `LegacyMap::<felt252, ContractAddress>` would make it easier to check if the username is taken already.

**Comment by mubarak23** [comment]
alright, but must the username be a `ContractAddress`  address, or it can be anything with type of  `felt252`

**Comment by b-j-roberts** [comment]
The username will be a `felt252`, so it can be set like : `let username: felt252 = 'brandon.stark'`, and the `ContractAddress` would store the user's address that claimed the username.
Hope that makes sense, and I understood your question properly

**Comment by mubarak23** [comment]
Interesting, this mean our storage contract will carry key-value pair of  username map to a ContractAddress.

understood, i will start working on it,
