### ISSUE TITLE
[feat] Frontend NFT pagination

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#170]
There are now pagination parameters on the getNFTs routes. We need to add buttons to the frontend on the bottom of my NFTs and all NFTs browsers to switch between pages.

#### References

- [NFT Panel](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/tabs/nfts/NFTs.js)
- [Get my NFTs route backend](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/backend/routes/nft.go#L55)
- [Get NFTs route backend](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/backend/routes/nft.go#L79)

**Comment by addegbenga** [comment]
I will like to work on this

**Comment by bitwise-del** [comment]
Can i work on this

**Comment by Joy-Adah** [comment]
Hi @b-j-roberts I indicated interest in the last community call for issues. Can I be assigned this?
