### ISSUE TITLE
[feat] Disconnect wallet button

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#173]
After connecting you wallet in the "Accounts" tab, it would be nice to add a button on the button to allow the user to disconnect w/ a "Disconnect Wallet" button.

#### References

- [Account tab](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/tabs/account/Account.js)

**Comment by muheebyusufbaba1** [comment]
i

**Comment by Oshioke-Salaki** [comment]
c

**Comment by Immanuelolivia1** [comment]
Can I work on this ?

**Comment by b-j-roberts** [comment]
@muheebyusufbaba1 Any updates on this, have you had time to work on it?

If not, I'd like to open up the issue for someone else to work on. Please submit a draft PR, if you can, of what you have started, and I can see how things are progressing on the issue.

**Comment by muheebyusufbaba1** [comment]
@b-j-roberts Yes I'll be sending a PR soon
