### ISSUE TITLE
[feat] Quest progress bar

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#175]
On the quest's frontend tab, the button to claim a quest is either red if not claimed or green if claimed. It'd be cool to have the button act like a progress bar aswell. So given 2 values `progress` and `needed`, say `needed=4` for example:

`progress = 0` -> full red button how it is now
`progress = 1` -> 1/4 full dark orange-ish
`progress = 2` -> 1/2 full orange-ish
`progress = 3` -> 3/4 full orange-yellow-ish
`progress = 4` -> full yellow and pulsing button indicating claimable

Then the button will be green after claiming like it is now. Make the colors be a steady transition based on the % of progress/needed. You can use hardcoded values for progress and needed for now.

#### References
- [Quest item ](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/tabs/quests/QuestItem.js)

**Comment by KeneePatel** [comment]
Would love to work on this :D

**Comment by KeneePatel** [comment]
Thank you for assigning me @b-j-roberts,

I have started working on it. I will be quick to complete the issue.

**Comment by KeneePatel** [comment]
Hey @b-j-roberts,

I wanted to know if there is any TG group for the project. I wanted to communicate and discussing on GH will just fill it up ig.
