### ISSUE TITLE
[feat] Get user quest status backend

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#176]
We will need 2 additional quest routes :
`get-quest-status` : gets the user's quest progression stats for main quests
`get-daily-quest-status` : gets the user's quest progression stats for daily quests

Have them take the address as a query parameter. Take the day index as another query parameter for the daily route.

Have the routes return a json like :
```
[
{
    "questId": quest1Id,
    "progress": value,
    "needed": value2
},
{
    "questId": quest2Id,
    "progress": value3,
    "needed": value4
},
...
]
```

Progress will indicate the users progress on the specified quest, and needed will indicate the maximum progress which indicates that the quest can be completed/claimed.
You can have them return hardcoded values for now.

#### References
- [Backend quest routes](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/quests.go)

**Comment by mubarak23** [comment]
@b-j-roberts can I work on this , kindly assign

**Comment by raizo07** [comment]
@b-j-roberts I'd like to be assigned
