### ISSUE TITLE
[feat] New day colors palette tracking

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#177]
Each new day colors are added to the palette. This is done onchain, but we must add the colors into our postgres colors table to show them on the frontend.

This issue is to create a `ColorAdded` event onchain, which triggers when a color is added to the palette. Then add a function to our indexer backend to add the color to our palette in postgres.

#### References
- [Colors table in postgres](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/postgres/init.sql#L93)
- [Onchain color added](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/onchain/src/art_peace.cairo#L1046)
- [Backend indexer routes](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/indexer/route.go)

**Comment by Immanuelolivia1** [comment]
I

**Comment by raizo07** [comment]
@b-j-roberts I'd like to be assigned to work on this.

**Comment by more-of-odeh** [comment]
Can i work on this please?

**Comment by Immanuelolivia1** [comment]
I'll summit a draft PR latter today

**Comment by Immanuelolivia1** [comment]
Please i will like to know how you got these const for the event indexerId 

<img width="1512" alt="Screenshot 2024-06-03 at 11 29 13" src="https://github.com/keep-starknet-strange/art-peace/assets/101520237/a52bdf87-6ac9-422d-b601-c5c4a3717962">




Also i'm having issues trying to format the .go files i ran the go fmt command locally and it word but the build still fails 

<img width="1508" alt="Screenshot 2024-06-03 at 11 24 55" src="https://github.com/keep-starknet-strange/art-peace/assets/101520237/eeddf8d8-8054-4b2e-8f3c-48d85afe4fd7">

**Comment by fishonamos** [comment]
@Immanuelolivia1, cd backend and go fmt ./...

**Comment by Immanuelolivia1** [comment]
> @Immanuelolivia1, cd backend and go fmt ./...

Thank you 
It has worked

**Comment by b-j-roberts** [comment]
@Immanuelolivia1 I left a comment on what the key is, but you can get the value using `starkli signature ColorAdded` for example.

Any updates on resolving the PR comments?
