### ISSUE TITLE
[feat] Next day votable colors events

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#178]
Each new day color votes are finalized and certain colors are moved from "VotableColors" to "Colors" in the palette. This is done onchain, but we must update the votable colors into our postgres VotableColors table to show them on the frontend.

This issue is to create a `VotableColorAdded` event onchain, which triggers when a color is added to the votable colors for the next day. Then add a function to our indexer backend to add the color to our votable colors in postgres.

Also, the Postgres table will need to be changed to track different days' votable colors, so the `day_idx` field will need to be added to the votable colors table. Also, the way the key is calculated will need to be changed since the key is currently used to know which color to vote for.

#### References
- [Votable colors table in postgres](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/postgres/init.sql#L100)
- [Onchain votable color added](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/onchain/src/art_peace.cairo#L1049)
- [Backend indexer routes](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/indexer/route.go)

**Comment by Gift-Naomi** [comment]
hi

**Comment by Iwueseiter** [comment]
can I work on this?

**Comment by more-of-odeh** [comment]
Can I be assigned to this please?

**Comment by b-j-roberts** [comment]
@Gift-Naomi   Any updates on this, have you had time to work on it?

If not, I'd like to open up the issue for someone else to work on. Please submit a draft PR, if you can, of what you have started, and I can see how things are progressing on the issue.

**Comment by Gift-Naomi** [comment]
@b-j-roberts I am working on it already I'll submit a PR today
