### ISSUE TITLE
[feat] Backend split into commands

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#179]
Currently, our backend is a monolithic setup. To make indexing and infra more secure, it would be good to split the backend into a few parts. Each would be launched with a different command. These parts can be :

`backend`: for main backend routes not included below
`indexer-consumer`: for all indexer-consuming functionality

#### References

- [Backend indexer stuff](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/indexer/route.go)
- [Example go command setup](https://github.com/b-j-roberts/MyBlockchains/tree/master/naive-blockchain/naive-cryptocurrency-l2/cmd)

**Comment by kateberryd** [comment]
Can I

**Comment by more-of-odeh** [comment]
Can i work on this please?

**Comment by Jemiiah** [comment]
@b-j-roberts i would love to contribute to this project
