### ISSUE TITLE
[feat] Quest: Faction quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#180]
Create a quest to check if a user has joined a faction.

Create corresponding tests.

#### References

- [Example Quest](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/rainbow_quest.cairo)
- [Faction info](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/onchain/src/art_peace.cairo#L40)

**Comment by kateberryd** [comment]
Hi

**Comment by mubarak23** [comment]
@b-j-roberts i have work on two quest similar to this, this will an interesting one, kindly assign

**Comment by kenkomu** [comment]
@b-j-roberts can I work on this?

**Comment by kenkomu** [comment]
Hello, my name is Kenneth Komu I am blockchain developer. I would implement it by adding a function in the RainbowQuest contract to return true if the user has joined a faction by verifying through the art_peace contract.

**Comment by b-j-roberts** [comment]
@kateberryd   Any updates on this, have you had time to work on it?

If not, I'd like to open up the issue for someone else to work on. Please submit a draft PR, if you can, of what you have started, and I can see how things are progressing on the issue.

**Comment by kateberryd** [comment]
Hi @b-j-roberts. Yes I'm working on it.  I'll create a PR today
