### ISSUE TITLE
[feat] Notification Panel

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#182]
Sometimes, there will be in-app notifications, like when a user's transaction is completed. It would be cool to have a notification panel animate in from the top. There will be a close button to close the panel, or it will animate back out of view after a few seconds.

A possible implementation would be to use `useEffect` to cause the panel to go into view when the notification message changes.

Please style the notification panel like other tabs.

**Comment by b-j-roberts** [comment]
Thank you for volunteering for the issue @raizo07. Please comment here and I can assign you

**Comment by raizo07** [comment]
Hi @b-j-roberts Kindly assign, thank you.

**Comment by kenkomu** [comment]
@b-j-roberts can I work on this?
