### ISSUE TITLE
[feat] Share NFT button

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#183]
It would be cool to add a button to each NFT on the "My NFTs" tab, allowing the user to share the NFT on Twitter or other socials.

Prioritizing the experience to share on Twitter would be ideal, but allowing more options would be cool.

#### References
- [My nfts frontend](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/tabs/nfts/NFTs.js)
- [NFT collection item](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/tabs/nfts/CollectionItem.js)

**Comment by b-j-roberts** [comment]
@Joy-Adah Thank you for volunteering, if you could comment here I can assign you!

**Comment by Oshioke-Salaki** [comment]
Can I have this?

**Comment by Joy-Adah** [comment]
@b-j-roberts I'm interested!

**Comment by Joy-Adah** [comment]
@b-j-roberts I'm interested!

**Comment by Joy-Adah** [comment]
@b-j-roberts I'm interested!
