### ISSUE TITLE
[bug] Extra Pixels panel patch spacing / overflows

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#184]
When placing extra pixels on the canvas, the "Extra Pixels Panel" appears on the right. The left side of the panel displays the different types of pixels available. The user can click the "Faction" option to expand more information.

The spacing and formatting of this tab can act weird when expanding the factions button. It would be good to fix issues with spacing and overflows caused by this.

#### References
- [Extra pixels panel frontend](https://github.com/keep-starknet-strange/art-peace/blob/main/frontend/src/tabs/canvas/ExtraPixelsPanel.js)
- [Factions button](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/frontend/src/tabs/canvas/ExtraPixelsPanel.js#L216)

**Comment by b-j-roberts** [comment]
@Oshioke-Salaki Thank you for volunteering for the issues. Please comment here if you'd like to take this!

**Comment by Immanuelolivia1** [comment]
i

**Comment by Oshioke-Salaki** [comment]
Please I am interested
