### ISSUE TITLE
[feat] Eraser mode indicator

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#185]
There is an "Erase" button on the extra pixels panel after placing pixels. However, after entering eraser mode, it would be helpful to indicate that the user is currently in that mode on the "Place Pixel" button.

When clicking a color you get the color on the RHS like in the image. When in eraser mode, this location should show an eraser icon instead.

![image](https://github.com/keep-starknet-strange/art-peace/assets/54774639/d6002170-37ad-4942-8616-94419f713d1d)

#### References
- [Extra pixels panel eraser](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/frontend/src/tabs/canvas/ExtraPixelsPanel.js#L191)
- [Place pixel button](https://github.com/keep-starknet-strange/art-peace/blob/60a872227573384f8a27ea5141b1b0f442effa94/frontend/src/footer/PixelSelector.js#L113)

**Comment by b-j-roberts** [comment]
@Jauxy thanks for volunteering to work on this issue. Please comment here and I can assign you!

**Comment by Jauxy** [comment]
Acknowledged, Thank you

**Comment by b-j-roberts** [comment]
> hi @b-j-roberts is there a telegram group for this project where I can join?

Hey @bhavyagosai , yes you can join here : @art_peace_starknet

**Comment by kenkomu** [comment]
Hello, my name is Kenneth Komu I am frontend developer and a blockchain developer. I will implement the issue by implementing a state variable to track eraser mode, update the "Place Pixel" button to indicate this mode, and display an eraser icon in the color display area when eraser mode is active. Thank you.

**Comment by b-j-roberts** [comment]
@Jauxy   Any updates on this, have you had time to work on it?

If not, I'd like to open up the issue for someone else to work on. Please submit a draft PR, if you can, of what you have started, and I can see how things are progressing on the issue.

**Comment by bhavyagosai** [comment]
If they are not available, you can pass on the issue to me if that's fine!

**Comment by Dprof-in-tech** [comment]
hello @b-j-roberts I'm Isaac, a Fullstack Javascript developer and i would love to work on this issue if the assigned person is not forthcoming

**Comment by b-j-roberts** [comment]
@bhavyagosai Would you still be interested in this issue?
