### ISSUE TITLE
[feat] Load Apibara script values from the environment

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#2]
Using `Deno.env.get`, load hostname, indexer and backend ports from environment variables in the Apibara scripts.

Then combine `docker-script.js` and `script.js` indexer scripts.

#### References

- [Apibara scripts](https://github.com/keep-starknet-strange/art-peace/tree/main/indexer)
- [Apibara docs](https://www.apibara.com/docs)

**Comment by TAdev0** [comment]
@b-j-roberts  may i be assigned to this issue? I have never worked on anything related to Apibara it could be a good start!

**Comment by b-j-roberts** [comment]
For sure, @TAdev0 could be a good issue to get an idea of what it's doing. Let me know if you have questions.
