### ISSUE TITLE
[feat] Quest Status Tracker: Username Quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#211]
This issue is to create a new `CheckUsernameStatus` function on the backend. This function will be used to return the user's progress on the `Username Quest` onchain.

The goal is to `return 0, 1` if the user does not have a username in the `Users` table on postgres, and `return 1, 1` if the user has a username in postgres.

Looking at other `CheckXStatus` functions should give good examples.

#### References
- [Quest status backend](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/backend/quests/status.go#L72)
- [Username table](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/postgres/init.sql#L31)
- [Username quest onchain](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/onchain/src/quests/username_quest.cairo#L40)

**Comment by b-j-roberts** [comment]
Hey @Soeten, thank you for volunteering for the issue. Can you comment here so I can
 assign you, if you are still interested?

**Comment by b-j-roberts** [comment]
Hey @Shoetan, thank you for volunteering for the issue. Can you comment here so I can
 assign you, if you are still interested?

**Comment by adrianvrj** [comment]
Hi, if this is still available I could work on this :)

**Comment by Shoetan** [comment]
Hi @b-j-roberts thank you so much. I would love to be assigned the issue.
