### ISSUE TITLE
[feat] Quest Status Tracker: NFT Quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#212]
This issue is to implement a `CheckNftStatus` function on the backend. This function will be used to return the user's progress on the `NFT Quest` onchain.

The goal is to `return 0, 1` if the user has not minted an NFT and `return 1, 1` if the user has minted an NFT. You can use postgres to query this info from the NFTs table.

Looking at other `CheckXStatus` functions should give good examples.

#### References
- [Quest status backend](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/backend/quests/status.go#L33)
- [NFTs table](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/postgres/init.sql#L158)
- [NFT quest onchain](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/onchain/src/quests/nft_quest.cairo#L36)

**Comment by b-j-roberts** [comment]
Hey @KeneePatel, thank you for volunteering for the issue. Can you comment here so I can assign you, if you are still interested?

**Comment by KeneePatel** [comment]
Yesser, I will try to finish it soon.
