### ISSUE TITLE
[feat] NFTs Explorer : New NFTs

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#214]
There will be various options for viewing NFTs, one will be to view "new" NFTs.

This issue is to create a new backend route to query the newest NFTs. To do this, sort by the NFT's token_id in descending order. The best way to do this will be to copy the `getNFTs` route and make the appropriate changes there.

Make sure to keep the pagination functionality working.

#### References
- [Get NFTs backend route](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/backend/routes/nft.go#L102)

**Comment by b-j-roberts** [comment]
Hey @Xaxxoo, thank you for volunteering for the issue. Can you comment here so I can assign you, if you are still interested?

**Comment by Xaxxoo** [comment]
Hi, I'm
Up
For it.
