### ISSUE TITLE
[feat] NFT explorer : Hot NFTs

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#216]
There will be various options for viewing NFTs, one will be to view "hot" NFTs.

This issue is to create a new backend route to query the hot NFTs.
This can be tricky to determine. I think the best way is to look at the latest likes in the NFTLikes table and use that to see which NFTs have received the most likes recently.
You can copy the `getNFTs` route and make the appropriate changes there.

Make sure to keep the pagination functionality working.

#### References
- [Get NFTs backend route](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/backend/routes/nft.go#L102)
- [NFT Likes table](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/postgres/init.sql#L169)

**Comment by EmmanuelAR** [comment]
Hey @b-j-roberts  can i work on this one? i understand that i have to make a query to get the hottest nfts

**Comment by EmmanuelAR** [comment]
thanks, i will working on it asap

**Comment by EmmanuelAR** [comment]
Hey @b-j-roberts idk if u have time to review the pr? thanks
