### ISSUE TITLE
[feat] Get Faction Members Route

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#217]
This issue is to add a route to the backend to get the faction members. The route will take the faction ID and pagination values as query parameters and return the list of members' usernames/addresses and allocations. Please sort the returned members based on allocation.

#### References
- [Example Pagination route](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/backend/routes/factions.go#L169)
- [Faction routes](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/factions.go)
- [Faction members table](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/postgres/init.sql#L198)

**Comment by b-j-roberts** [comment]
Hey @adrianvrj, thank you for volunteering for the issue. Can you comment here so I can assign you, if you are still interested?

**Comment by adrianvrj** [comment]
Sure, I can work on this!
