### ISSUE TITLE
[feat] Onchain NFT likes/dislikes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#218]
This issue is to create 2 functions on the `CanvasNFTStore` component for liking and unliking NFTs.

These routes will only emit events for `NFTLiked` and `NFTUnliked`, with the user address and token id as fields. There will be no onchain storage for likes, making these methods cheap to call.

#### References
- [Canvas NFT Store](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/nfts/component.cairo)

**Comment by b-j-roberts** [comment]
Hey @mubarak23 , thank you for volunteering for the issue. Can you comment here so I can assign you, if you are still interested?

**Comment by mubarak23** [comment]
@b-j-roberts kindly assigned 

thank you

**Comment by mubarak23** [comment]
- Can you explain what you mean by “no storage for likes “
- Can you point me to where  this function will be call after they are implemented @b-j-roberts

**Comment by b-j-roberts** [comment]
> * Can you explain what you mean by “no storage for likes “

There will be no storage variables to track how many likes an nft has, or if a user has liked an nft onchain. It will all be tracked off chain.

> * Can you point me to where  this function will be call after they are implemented @b-j-roberts

It will be called directly by the user on the frontend

**Comment by mubarak23** [comment]
> > * Can you explain what you mean by “no storage for likes “
> 
> There will be no storage variables to track how many likes an nft has, or if a user has liked an nft onchain. It will all be tracked off chain.
> 
> > * Can you point me to where  this function will be call after they are implemented @b-j-roberts
> 
> It will be called directly by the user on the frontend

the call the user will do is by calling a function from CanvasNFT contract right,

so this mean i will expose two function inside CanvasNFT contract that expose the two CanvasNFTStoreComponent like and unlike

**Comment by b-j-roberts** [comment]
Yes thats right. You can create a new trait for the like functions and expose/implement them in the canvas nft contract
