### ISSUE TITLE
[feat]: Check if redis is actually running 

### ISSUE THREAD

**Issue by lfgtwo** [keep-starknet-strange/art-peace#228]
#### References

The following problem was found when running local integration tests

**reproduction**
1. `redis-server &`  first run redis
2. `make integration-test-local`

```shell
Starting redis server ...
1165:signal-handler (1717951231) Received SIGTERM scheduling shutdown...
1165:M 10 Jun 2024 00:40:31.694 * User requested shutdown...
1165:M 10 Jun 2024 00:40:31.694 * Saving the final RDB snapshot before exiting.
1165:M 10 Jun 2024 00:40:31.698 * DB saved on disk
1165:M 10 Jun 2024 00:40:31.698 # Redis is now ready to exit, bye bye...
[1]  + 1165 done       redis-server
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Failed to start Redis.  // add a ping/pong check
```

so after `sleep 2`, maybe at this time redis-server is not restart.The next `redis-cli del canvas` command may be affected, so we need check if redis is actually running

**Comment by Ugo-X** [comment]
Hello my name is Ugo and i am full stack Dev please can i be assigned this task?

**Comment by b-j-roberts** [comment]
Hey @lfgtwo , thanks. The local integration test hasn't been maintained so it won't really launch the app properly anyway. So this isn't really a focus at the moment.
