### ISSUE TITLE
[feat] Quest Status Tracker: Hodl Quest

### ISSUE THREAD

**Issue by lfgtwo** [keep-starknet-strange/art-peace#236]
for `HODL` quest:
```
      {
        "name": "HODL",
        "description": "Accumulate 10 extra pixels in your account",
        "reward": 5,
        "questContract": {
          "type": "HodlQuest",
          "initParams": [
            "$ART_PEACE_CONTRACT",
            "$REWARD",
            "10"
          ],
          "storeParams": [2]
        }
      },
```

The goal is to return 0, 1 if the user not accumulate 10 extra pixels and return 1, 1 if the user has accumulate 10 extra pixels.

#### References

- [CheckHodlStatus](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/backend/quests/status.go#L28)
- relative table:`ExtraPixels`

**Comment by adrianvrj** [comment]
Hi! Can I work on this?

**Comment by lfgtwo** [comment]
> Hi! Can I work on this?

I already working on it

**Comment by b-j-roberts** [comment]
Hey @lfgtwo , this description is not fully accurate.
The quest status should return `progress`, `needed`. So in this example it would be `extra_pixels`, `needed_extra_pixels`. Which are both variable based on the quest description

**Comment by lfgtwo** [comment]
> initParams
got it sir
1. `needed_extra_pixels ` is storeParams, just get from `Quest.InputData`
2. for `extra_pixels ` just get for db  similar like `available, err := core.PostgresQueryOne[string]("SELECT available FROM ExtraPixels WHERE address = $1", address)`

If there is any problem with the above understanding, please feel free to point it out.
> You'll need to create type for that as well

not clear for this part
