### ISSUE TITLE
[feat] Quest Status Tracker: Rainbow Quest

### ISSUE THREAD

**Issue by lfgtwo** [keep-starknet-strange/art-peace#238]
- Rainbow config:
```
      {
        "name": "The Rainbow",
        "description": "Place at least 1 pixel of each color",
        "reward": 10,
        "questContract": {
          "type": "RainbowQuest",
          "initParams": [
            "$ART_PEACE_CONTRACT",
            "$REWARD"
          ],
          "storeParams": []
        }
      }

```
This issue is to implement a `CheckRainbowStatus` function on the backend. This function will be used to return the user's progress on the Rainbow Quest onchain.

#### References
- [Colors table](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/postgres/init.sql#L114)
- [Pixels table](https://github.com/keep-starknet-strange/art-peace/blob/8b1f8bc6a66b6f5246cf813b641ed0b908a29405/postgres/init.sql#L3)

**Comment by stevencartavia** [comment]
Hi, can I take this?

**Comment by lfgtwo** [comment]
@b-j-roberts sir,I think issues are being monitored. Someone commented as soon as I created it.lol

**Comment by b-j-roberts** [comment]
This issue description is not completely accurate @lfgtwo , I'd look at the other issue comment I made for details.
