### ISSUE TITLE
art/peace Contest Winners

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#250]
Comment here with your art piece's name and your username from the art/peace competition if you were one of the winners mentioned.

Thank you!

**Comment by kimlabu** [comment]
Hi Brandon
I'm Kimlabu
Fibrous
Many thanks
![Ekran görüntüsü 2024-07-17 120706](https://github.com/user-attachments/assets/3e32812d-616b-4d01-929c-208f16366e85)

**Comment by msjoedor** [comment]
Hi, 

I'm Jo and my art-peace design in collaboration with EncompassWell was "Much Love LGBTQ+"

Thank you so much!

<img width="431" alt="Screenshot 2024-07-17 at 10 22 44" src="https://github.com/user-attachments/assets/9ef09347-2626-416b-9c17-44aed6a49b0b">

**Comment by coingeener** [comment]
Hi
Im Coingeener,
I prepared the flag of Turkey.
<img width="463" alt="Ekran Resmi 2024-07-17 12 35 32" src="https://github.com/user-attachments/assets/fbdcbf4e-83f8-47ea-9e5b-92250dd78550">

**Comment by EncompassWellHQ** [comment]
Hi!

We are EncompassWell and we collaborated with @msjoedor on "mUCH LOVE! lgbtq+"

It really was fun <3
<img width="423" alt="Screenshot 2024-07-17 at 10 40 36" src="https://github.com/user-attachments/assets/268e0ac0-be29-4893-9905-7dee30713ecf">

**Comment by Metronomy** [comment]
Hello!
Im Angelo (username "Angelo" on Art/Peace) and drew the E-Beggar.

Thank you!

**Comment by MarkyB71** [comment]
![image](https://github.com/user-attachments/assets/4ab0d413-5d62-4ccb-9a73-ef7e7430a1f1)
Hi, I'm Skippy part of the Starknet/Influence fractions contribution.

**Comment by dreamvisual** [comment]
![account](https://github.com/user-attachments/assets/5171f3db-199e-4168-975d-8c5f6194a238)
fb)
hi 
I am Dream visual i made the dream art without the Starknet word type

**Comment by Adriano9811** [comment]
![art](https://github.com/user-attachments/assets/8f43288d-fd77-4076-8409-6919904fb186)
Hi, i'm Adriano and I made Starkwolfi.

**Comment by mecha-cygnus** [comment]
Hello,

I'm mecha and I made the "QuantumCAT" artwork.
Thank you!

![mecha-art-peace](https://github.com/user-attachments/assets/adcde2d2-c167-4a3f-9149-80fba5b34bb8)

**Comment by cnicules** [comment]
Hi,
Prici here with 1St Pingu
![Screenshot 2024-07-17 at 18 28 49](https://github.com/user-attachments/assets/e6954ae7-a2e8-4061-8cbd-475a73255045)
Cheers

**Comment by AnoukRImola** [comment]
Hello Brandon!
I am Azula_ro and I created 0xTV , thank you guys!  :)
![image](https://github.com/user-attachments/assets/a851c045-b500-400b-963b-d3250a8c662e)

**Comment by FaFqt** [comment]
Hello,

I'm FaFqt. I made the "Pika Pika" artwork.

Thank you guys !

![image](https://github.com/user-attachments/assets/c2c38b0b-5b3f-45a5-a448-d3cf42752b85)

**Comment by fcatalao** [comment]
![image](https://github.com/user-attachments/assets/becd637b-5c6d-4396-b114-6b42295b5875)
Hi guys, 
my wallet fabiocatalao.stark

**Comment by fcatalao** [comment]
![image](https://github.com/user-attachments/assets/5ded0232-7de3-4e01-97ef-518d07177d9c)

**Comment by kimlabu** [comment]
Hi,

I'm kimlabu and I made fibrous artwork (nick:kimlabu1).

Many thanks

Fabio Catalão ***@***.***>, 19 Tem 2024 Cum, 15:08 tarihinde
şunu yazdı:

**Comment by OutSmth-qq** [comment]
Heyy Brandon,

OutSmth, Ducks Everywhere faction leader
![Capture d’écran 2024-07-21 090413](https://github.com/user-attachments/assets/7e7888ca-9511-4550-bfd3-87f38053d2f1)

**Comment by behtin** [comment]
> Comment here with your art piece's name and your username from the art/peace competition if you were one of the winners mentioned.
> 
> Thank you!

Thanks Brandon . my nft is starkwolf
<img width="435" alt="Screenshot 2024-07-22 at 9 47 26 PM" src="https://github.com/user-attachments/assets/07f9e3c5-6d81-44a6-9a23-e139cea94b76">

**Comment by b-j-roberts** [comment]
> Hi,
> 
> I'm Jo and my art-peace design in collaboration with EncompassWell was "Much Love LGBTQ+"

Would you like me to split to 1K between y'all? If so how would you like the split, just a percentage based on Pixels placed?

**Comment by msjoedor** [comment]
@b-j-roberts Hey Brandon! 
Let it all come to mine, i would do the split myself.

Thank you for reaching out!

**Comment by msjoedor** [comment]
Hey Brandaon! @b-j-roberts 

Yes please, on second thought a percentage split based on pixels works.

Thank you for reaching out!

**Comment by Antoine-Sparenberg** [comment]
Hi there !

Antoine here, Argent faction leader

Username: moretps

We will redistribute the prize to participants, either prorata-based or in a lottery


![image](https://github.com/user-attachments/assets/c7e90a36-5560-4212-b7eb-55aae71360c3)

**Comment by cnicules** [comment]
looks like i have 2 claims, Cheers
![Screenshot 2024-07-31 at 20 25 50](https://github.com/user-attachments/assets/db431ef5-1530-49b4-84ed-aeab7e6e5f87)
