### ISSUE TITLE
art/peace Award Winners

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#251]
If you won an award in the art/peace contest, please follow these steps : 

1. Create a [github account](https://github.com/) if you dont have one.
2. Sign up for [OnlyDust](https://app.onlydust.com/) and create a Billing Profile with your Starknet account used in the art/peace competition.
3. Comment on this Github issue with a photo of your account page and what awards you qualify for.

Thank you!

Please submit a photo like this and list your awards from the "How to Claim" page.
![image](https://github.com/user-attachments/assets/03d22fb7-8f60-46fe-b06b-4460445ea85f)

Then your awards will be soon distributed.

**Comment by EjembiEmmanuel** [comment]
@b-j-roberts 

![image](https://github.com/user-attachments/assets/7866dbc6-4ad0-43af-ae8b-99e221c45ae6)

**Comment by 0xandee** [comment]
<img width="1231" alt="image" src="https://github.com/user-attachments/assets/c9fed806-5715-4930-b1ad-cde9c0f0ab46">

**Comment by StarkyTheDoggo** [comment]
![art-peace](https://github.com/user-attachments/assets/28181719-605a-4842-b031-4ff89c91305d)

**Comment by behtin** [comment]
> If you won an award in the art/peace contest, please follow these steps :
> 
> 1. Create a [github account](https://github.com/) if you dont have one.
> 2. Sign up for [OnlyDust](https://app.onlydust.com/) and create a Billing Profile with your Starknet account used in the art/peace competition.
> 3. Comment on this Github issue with a photo of your account page and what awards you qualify for.
> 
> Thank you!
> 
> Please submit a photo like this and list your awards from the "How to Claim" page. ![image](https://private-user-images.githubusercontent.com/54774639/351451760-03d22fb7-8f60-46fe-b06b-4460445ea85f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzcxNjksIm5iZiI6MTcyMjI3Njg2OSwicGF0aCI6Ii81NDc3NDYzOS8zNTE0NTE3NjAtMDNkMjJmYjctOGY2MC00NmZlLWIwNmItNDQ2MDQ0NWVhODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE4MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMjMwMzkyOGZmMGI1MDQ0NDdiOWUyOWJlMmY1MjFmNWE5ZDRkYjY3YWEyY2IxYmJlMzgwOTBkODE5ODhiNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TCBMC8MwTyXDJhx1Pe0GCQ2yub6q7g0yxKJY8xLBIU4)
> 
> Then your awards will be soon distributed.

![Uploading Screenshot 2024-07-29 at 10.15.07 PM.png…]()

**Comment by behtin** [comment]
![Uploading Screenshot 2024-07-29 at 10.15.07 PM.png…]()

**Comment by behtin** [comment]
<img width="1440" alt="Screenshot 2024-07-29 at 10 15 07 PM" src="https://github.com/user-attachments/assets/c68486e4-f25b-49a0-9c7f-442b797b661e">

**Comment by coingeener** [comment]
<img width="929" alt="Ekran Resmi 2024-07-29 23 11 29" src="https://github.com/user-attachments/assets/f8f31949-965b-4e10-990d-415ac347978c">

1st 100 Alpha Wolves : 25STRK
Community Effort: Influence : 22STRK

**Comment by ekinmistik** [comment]
<img width="962" alt="Ekran Resmi 2024-07-29 23 23 28" src="https://github.com/user-attachments/assets/519bc8b3-cb3a-46d9-9a8f-9dc3b73bdec5">

1st 100 Alpha Wolves : 25STRK

Does Onlydust require KYC? I wrote my wallet address there.

**Comment by busracimir** [comment]
<img width="976" alt="Ekran Resmi 2024-07-29 23 28 40" src="https://github.com/user-attachments/assets/dd8b2919-86ca-473f-b0cc-36422a98131e">
1st 100 Alpha Wolves : 25STRK

**Comment by MarkyB71** [comment]
![image](https://github.com/user-attachments/assets/60cb2c17-9c2d-49e6-81c6-e496dbf5626b)

**Comment by Cologan** [comment]
![Screenshot 2024-07-29 223533](https://github.com/user-attachments/assets/10318111-b469-4738-be2b-ffc9ad146a55)

1st Alpha Wolves: 25STRK
Chain Wars Participant: Starknet: 180 STRK
Community Effort: Influence: 56 STRK

**Comment by FaFqt** [comment]
Oh ! Thank you guys !
Also qualified of 1st 100 alpha wolves !! 
A great pleasure to have been able to participate in this project !! 🫶🏻
<img width="931" alt="Capture d’écran 2024-07-29 à 22 44 55" src="https://github.com/user-attachments/assets/66e58796-b600-48c6-8773-3456ddca8124">

**Comment by machuwey** [comment]
<img width="441" alt="image" src="https://github.com/user-attachments/assets/711c8a6f-c9cf-4f2e-ba3b-1d578139b5e2">
1st 100 Alpha Wolves : 25STRK

**Comment by mrMateosantana** [comment]
<img width="925" alt="image" src="https://github.com/user-attachments/assets/bc3eeeb9-fa8f-40ae-9a27-ca31dc67fec5">

Community Effort: Ducks Everywhere : 94STRK

**Comment by ProfSabre** [comment]
![image](https://github.com/user-attachments/assets/eb08eab7-c859-4ddb-ad94-60d54aa54204)

1ST 100 Alpha Wolves: 25 STRK
1ST 100 - Random Winner: 1000 STRK

And thank you!

**Comment by AnoukRImola** [comment]
![image](https://github.com/user-attachments/assets/0123223e-7d0a-4135-83e3-55ebdfe6302e)
Thank you guys!

**Comment by bobihs** [comment]
![545~NI{AH%0}IU8HLKVJ)UP](https://github.com/user-attachments/assets/fd348be9-d3b3-46d6-8e0e-a1608f8b79fb)

**Comment by bobihs** [comment]
![image](https://github.com/user-attachments/assets/c0fb68ad-595a-4727-9d9d-e4bce871d326)

**Comment by 232234221** [comment]
![SW8WDWC$NJXOZXNFD4DG8I4](https://github.com/user-attachments/assets/78e7cf81-d824-4cb6-b179-8d3211c235ce)

**Comment by Jdyhds** [comment]
![image](https://github.com/user-attachments/assets/0b6bc10a-a220-48a8-936b-79b8cd188454)

**Comment by phanphuocdat** [comment]
![2](https://github.com/user-attachments/assets/162d29b6-8ae6-4124-b214-b4dc954102b8)

**Comment by raizo07** [comment]
<img width="1512" alt="Screenshot 2024-07-30 at 04 01 25" src="https://github.com/user-attachments/assets/340b538d-7488-4d1d-b13b-227bd1f55dd9">

1st Alpha Wolves: 25STRK
Community Effort: Influence: 24 STRK

**Comment by LiesLiesLiesoO** [comment]
![Безымянdный](https://github.com/user-attachments/assets/76accccf-813b-4c8b-8471-794e31cde313)

**Comment by 1313131313745** [comment]
![Безымяннsый](https://github.com/user-attachments/assets/1bec54c1-9cce-4593-b381-b2b1d816b870)

0x050133EA8F3BA5970f40c72df904359bb9600762b5B38b0F0f92a70EA2164b1B

**Comment by 1313131313745** [comment]
![БезымяннЫЫЙЫsый](https://github.com/user-attachments/assets/010cb274-91e3-43c9-97be-15869752e0ac)

0x050133EA8F3BA5970f40c72df904359bb9600762b5B38b0F0f92a70EA2164b1B

**Comment by dwffgwerghehwrhe** [comment]
![Безымяdwswdqqwdнный](https://github.com/user-attachments/assets/d1277d27-5e63-43a1-bb27-74b3d55a04fe)

Bitcoin : 63STRK
0x02B4E63eC61eDdb4714A81205314f3881e847BA7DB938E02D25D14B2FFC6026B

**Comment by erfqerghqerhqerhqerh** [comment]
![Безыsмяdнный](https://github.com/user-attachments/assets/396f6de8-81e4-4b82-b86d-cb45dc679ea3)

**Comment by Antoine-Sparenberg** [comment]
moretps.stark

![image](https://github.com/user-attachments/assets/c80710f8-1090-41a2-bcda-5c9d42987fc1)

**Comment by OkoliEvans** [comment]
![image](https://github.com/user-attachments/assets/b64008f8-3b93-4a45-ba23-28bf42fa21de)

**Comment by cwwegwegwgewge** [comment]
![Безымsянный](https://github.com/user-attachments/assets/5c29a601-6ecb-4509-bade-b3a26c1b1442)

54 STRK
0x074e532b4C060FBbd4EA396fb145d3201B6e0B053045c6F15568CbF1D8f4b3c0

**Comment by mecha-cygnus** [comment]
![artpeace](https://github.com/user-attachments/assets/6103c4ec-6290-44ad-a6e1-efd7c1c0c0d8)

**Comment by rhtrthrtjwwrtjwrtjrjgwedqwgeqwegweg** [comment]
![Безымsянный](https://github.com/user-attachments/assets/53a84dab-41b2-4ef0-982e-acf57a3e63b5)

**Comment by weqweqerhqerhqherqehrqher** [comment]
![Безыsмянный](https://github.com/user-attachments/assets/78441b35-1576-43c6-b874-7a31b2ffd763)

0x0088F0fb225cf84fC1112b3bab9d6e3317b7028553509eCA6172c3638A534F3e

**Comment by Yujiaau** [comment]
![image](https://github.com/user-attachments/assets/187945ef-6f19-4d03-86ea-fd341a5097bc)

**Comment by Pololopu** [comment]
![image](https://github.com/user-attachments/assets/4b89bad7-702d-4a3b-a2d0-f17ee4e846f8)

**Comment by Tanzbxx** [comment]
![image](https://github.com/user-attachments/assets/77fd5b62-aa6f-4c9a-b0c5-24cdf30008d9)

**Comment by 889love** [comment]
![image](https://github.com/user-attachments/assets/0649dd55-bd79-4548-87aa-c7b33e15881f)

**Comment by 0xtoujou** [comment]
<img width="1179" alt="Capture d’écran 2024-07-30 à 11 15 54" src="https://github.com/user-attachments/assets/616f4173-9697-4d2b-8ac4-d469ac571fb6">


1ST 100 Alpha Wolves: 25 STRK

**Comment by kimlabu** [comment]
![Screenshot_2024-07-30-13-00-34-645_app braavos wallet-edit](https://github.com/user-attachments/assets/a2303a47-fe2b-4c29-bc76-6930aad75592)
![Screenshot_2024-07-30-13-03-15-544_app braavos wallet-edit](https://github.com/user-attachments/assets/1def96d9-2166-4686-83fc-b02f87d40a88)

Hi everyone
im kimlabu (kimlabu1)
Many thanks 

1st 100 Alpha Wolves : 25 STRK
Community Effort: Influence : 56 STRK

**Comment by Yugfed** [comment]
![image](https://github.com/user-attachments/assets/e7dcc6a6-c417-49bc-ab68-1217eecc1442)

**Comment by Mazelecta** [comment]
![Capture d'écran 2024-07-30 185948](https://github.com/user-attachments/assets/3119b264-7956-4313-8bc7-239fb5d78770)

**Comment by ertemtisli** [comment]
<img width="972" alt="Ekran Resmi 2024-07-31 02 53 10" src="https://github.com/user-attachments/assets/8c4622cf-bbcc-4aa6-b54c-3afb94753571">

**Comment by d3lta02** [comment]
![delta-art - Copy](https://github.com/user-attachments/assets/44eff8b5-2424-4124-9d0d-9b5944414f75)

**Comment by huahua1220** [comment]
![image](https://github.com/user-attachments/assets/b10f85e6-fd1e-4f08-a6ad-aacfdf335147)

**Comment by hhhua1** [comment]
![image](https://github.com/user-attachments/assets/4242994e-7313-4674-982b-c0039a610962)

**Comment by Dadw423** [comment]
![image](https://github.com/user-attachments/assets/1dfa243d-8e5c-4fad-b57f-a3ef17f87248)

**Comment by CavilV** [comment]
![image](https://github.com/user-attachments/assets/1fb990d8-64aa-4d9f-ab87-fcdac6f9b7b6)

**Comment by ad3dfff** [comment]
![image](https://github.com/user-attachments/assets/c0572e5b-5404-4115-a54a-2a79368e6b45)
1st 100 Alpha Wolves : 25STRK
Chain Wars Participant: Base : 93STRK

**Comment by Haneabelow** [comment]
![image](https://github.com/user-attachments/assets/ee96a6c3-f76f-45b5-b294-a438b6eab85e)
42 STRK

**Comment by player-86** [comment]
![Ekran görüntüsü 2024-08-12](https://github.com/user-attachments/assets/9cd4adbf-9e22-4658-9e5b-11d4a27da25b)

**Comment by strwrsfrk** [comment]
![Screenshot 2024-09-08 at 9 47 04 AM](https://github.com/user-attachments/assets/1099cb78-6529-4d1f-92f9-156b85c3970a)

**Comment by b-j-roberts** [comment]
Thanks, everyone, for participating, I will close this issue now that rewards have been distributed!
