### ISSUE TITLE
Worlds URLs based on name

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#268]
We would like each "World" in art/peace to have a unique url/path. Currently, after creating a world in the Worlds tab, you can navigate to it by selecting it, which will open `http://localhost:3000/worlds/<world-id>`. We would like to create an alternate route which is more human readable, something like `http://localhost:3000/world/<world-name>`.

To do this we will need to add these checks for world creations.
Frontend & onchain contract checks:
- Ensure the name only contains letters, numbers, spaces, hyphens, and underscores
- Ensure the name is unique on both frontend ( when creating ) and onchain when create_canvas is called ( I'd recommend following the same pattern used for usernames uniqueness checks on [frontend](https://github.com/keep-starknet-strange/art-peace/blob/091610cb9056aae2b2e042b9b7520631b4d78422/frontend/src/tabs/account/Account.js#L228), [backend](https://github.com/keep-starknet-strange/art-peace/blob/091610cb9056aae2b2e042b9b7520631b4d78422/backend/routes/user.go#L248), and [onchain](https://github.com/keep-starknet-strange/art-peace/blob/091610cb9056aae2b2e042b9b7520631b4d78422/onchain/src/username_store/username_store.cairo#L53) )

The `<world-name>` in the url will be a lowercase and hyphen separated ( so convert all letters to lowercase from the name and spaces to hyphens ). We will need to ensure this transformed name is unique when creating the world.

**Comment by supreme2580** [comment]
@b-j-roberts can I be assigned to this?
