### ISSUE TITLE
Round 3 Competition "Join" button

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#270]
Currently when creating a "world", the user has the option to imput custom: Name, Size, Timer, Color Palette, Start Time, End Time.

For round 3 of the game, if a user want to create a world to join the round 3 competition, they will need to create a world with a specific Timer, Start Time, and End Time value.
This issue is to add a "Join Round 3" toggle button to the worlds creation screen, which when toggled disable/hide the inputs for Timer, Start Time, and End Time in the world creation form and show a hardcoded value indicating the specific Timer, start time, and end time for worlds that are a part of the competition. ( Say 5 seconds, Dec 6th, Jan 1st respectively for testing )

We can hardcode the values into the frontend for now, or if you'd like to put in extra effort, we can add them to one of the config files and query these values from the backend.

Make "Join Round 3" toggle default to true for now.

**Comment by raizo07** [comment]
@b-j-roberts can I work on this?

**Comment by supreme2580** [comment]
@b-j-roberts can I be assigned to this?
