### ISSUE TITLE
[feat] Quest: Create a "Deploy an Unrugabble Memecoin" quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#28]
Create a new quest type denoting the quest "Deploy an Unrugabble Memecoin" .

Have the `is_claimable` / `claim` functions take the address of the `UnruggableMemecoin` as `calldata[0]`, then properly check that the user address is the owner of the Memecoin. Also, check the appropriate "Additional functions" in the Unruggable Contract Interface to ensure that the token is a deployed `UnruggableMemecoin`.

Create a mock contract for the needed `UnruggableMemecoin` interfaces to create test cases.

#### References
- [Unruggable Memecoin GitHub](https://github.com/keep-starknet-strange/unruggable.meme)
- [Unruggable Contract Interface](https://github.com/keep-starknet-strange/unruggable.meme/blob/main/contracts/src/token/interface.cairo)
- [Unruggable website](https://unruggable.meme)
- [PixelQuest Example](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/pixel_quest.cairo)

**Comment by OkoliEvans** [comment]
Can I work on this too? @b-j-roberts

**Comment by b-j-roberts** [comment]
Sure @OkoliEvans . Let me know if you have any questions.

**Comment by b-j-roberts** [comment]
Hey @OkoliEvans , I'll be unassigning this for now while you work on the other issue.

**Comment by TAdev0** [comment]
@b-j-roberts may I be assigned to it?

**Comment by b-j-roberts** [comment]
For sure @TAdev0 , let me know if you have questions.

**Comment by OkoliEvans** [comment]
Okay, that's fair

**Comment by TAdev0** [comment]
@b-j-roberts  sorry i forgot to specify ''close # .. ' in the PR. This issue is completed and can be closed.
