### ISSUE TITLE
[feat] Quest: Create a "Add template" quest

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#29]
Create a quest that checks if a user has successfully added a template to the `ArtPeace` contract.

Add a field to the `TemplateMetadata` for the `creator`, which is set to the caller address when `add_template` is done.

Have the add template quest take the `template_id` as `calldata[0]` and check that the `creator` of the template at that id within the `ArtPeace` contract does match the user address.

#### References
- [Template Metadata](https://github.com/keep-starknet-strange/art-peace/blob/5d71f79a5fc1a7fbfd758bc2646d9e26c48f5cfb/onchain/src/templates/interface.cairo#L2)
- [PixelQuest Example](https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/pixel_quest.cairo)

**Comment by mubarak23** [comment]
So, `TemplateMetadata` will carry creator field with type of `felt252`, then add another function inside the interface, called `add_template`, then implement it inside `PixelQuest `contract

am i correct here

**Comment by mubarak23** [comment]
@b-j-roberts  can you assign this issue to me, i will work on it

**Comment by mubarak23** [comment]
@b-j-roberts Can you please explain this part “ create an entirely new quest and implement the IQuest interface. “

**Comment by b-j-roberts** [comment]
> @b-j-roberts Can you please explain this part “ create an entirely new quest and implement the IQuest interface. “

You should create a quest contract with the specs from the other comment. You can use this quest as a reference : https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/quests/pixel_quest.cairo

**Comment by b-j-roberts** [comment]
Template id and metadata is stored in the template store component https://github.com/keep-starknet-strange/art-peace/blob/main/onchain/src/templates/component.cairo#L12

template id is already setup in add_template, so no need to worry about it. Just checking that a template was added by the creator to show they completed the quest. You'll use the art peace contract and dispatcher to check the data.

**Comment by mubarak23** [comment]
alright, so it is inside is_claimable that i will check creator field is the same with template_id,  and it is inside add_template that we set creator field from the TemplateMetadata,

**Comment by mubarak23** [comment]
is my contract implementing all Quest interface as seen inside PixelQuest

**Comment by b-j-roberts** [comment]
> alright, so it is inside is_claimable that i will check creator field is the same with template_id, and it is inside add_template that we set creator field from the TemplateMetadata,

Yes, to both.
You'll check the creator is the user on is_claimable.

**Comment by b-j-roberts** [comment]
> is my contract implementing all Quest interface as seen inside PixelQuest

Just the `IQuest` interface, not the `IPixelQuest` interfaces.
