### ISSUE TITLE
[feat] Create production flag on the backend

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#3]
Create a `production` command line flag for the Go backend.

Then use the flag to disable Devnet routes like `placePixelDevnet`.

#### References
- [Commandline args](https://github.com/keep-starknet-strange/art-peace/blob/f69b4acdd82303a4c512261dd5ae91ca80d6fde4/backend/main.go#L12)
- [Example to disable](https://github.com/keep-starknet-strange/art-peace/blob/f69b4acdd82303a4c512261dd5ae91ca80d6fde4/backend/routes/pixel.go#L18)

**Comment by ptisserand** [comment]
Hi @b-j-roberts, can I work on this one ?

**Comment by b-j-roberts** [comment]
Definitely, @ptisserand ! Welcome to the project!
