### ISSUE TITLE
[feat] Template ERC20 rewards deposit

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#30]
Add the functionality to deposit the `reward` from the `reward_token` in the `add_template` function call. Make sure to revert if the deposit fails at any step.

#### References
- [Template add_template func](https://github.com/keep-starknet-strange/art-peace/blob/5d71f79a5fc1a7fbfd758bc2646d9e26c48f5cfb/onchain/src/templates/component.cairo#L55)
- [ERC20 deposit example](https://github.com/keep-starknet-strange/succinct-starknet/blob/11b2139427a34b5aaf764eab4db77942e8b5fb60/src/fee_vault.cairo#L144)

**Comment by TAdev0** [comment]
@b-j-roberts  may i be assigned to this issue?
