### ISSUE TITLE
[feat] Template distribute rewards

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#31]
Add functionality to the `complete_template` function to distribute the template reward to all the template builders.
Reward each user proportionally to the amount of pixels they placed that matched the template. Use the `owner` field of the `Pixel` to determine who to reward.

#### References
- [Pixel owner](https://github.com/keep-starknet-strange/art-peace/blob/5d71f79a5fc1a7fbfd758bc2646d9e26c48f5cfb/onchain/src/interface.cairo#L6)
- [Template complete func](https://github.com/keep-starknet-strange/art-peace/blob/5d71f79a5fc1a7fbfd758bc2646d9e26c48f5cfb/onchain/src/art_peace.cairo#L446)
- [ERC20 transfer example](https://github.com/keep-starknet-strange/succinct-starknet/blob/11b2139427a34b5aaf764eab4db77942e8b5fb60/src/fee_vault.cairo#L200)

**Comment by OkoliEvans** [comment]
I will love to take this issue @b-j-roberts

**Comment by b-j-roberts** [comment]
Awesome, I'll assign you @OkoliEvans. Welcome to the project!

**Comment by OkoliEvans** [comment]
> @OkoliEvans are you working on it?

Yes

**Comment by mubarak23** [comment]
@OkoliEvans are you still working on this, 
@b-j-roberts can I take this

**Comment by OkoliEvans** [comment]
> @OkoliEvans are you still working on this, @b-j-roberts can I take this

I am almost done with this, just trying to get the testing completed and that's it. You can check other issues.
