### ISSUE TITLE
[feat] Pass pixel position instead of (x, y) 

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#4]
Have the `placePixelDevnet` function take `position` instead of `x` and `y` arguments. 

Change calls on the frontend to reflect this change.

#### References

- [Backend](https://github.com/keep-starknet-strange/art-peace/blob/f69b4acdd82303a4c512261dd5ae91ca80d6fde4/backend/routes/pixel.go#L68)
- [Frontend](https://github.com/keep-starknet-strange/art-peace/blob/f69b4acdd82303a4c512261dd5ae91ca80d6fde4/frontend/src/Canvas.js#L216)

**Comment by addegbenga** [comment]
I will like to work on this issue

**Comment by b-j-roberts** [comment]
Awesome, I'll assign you @addegbenga . Welcome to the project!

The position is encoded as `position = x + y * canvas_width` if its not clear from the issue.

**Comment by addegbenga** [comment]
> Awesome, I'll assign you @addegbenga . Welcome to the project!
> 
> The position is encoded as `position = x + y * canvas_width` if its not clear from the issue.

Okay got it.

**Comment by addegbenga** [comment]
@b-j-roberts i am getting an error trying to run docker compose it keeps failing when installing apibara :
And the error seems to be related to this pr raised on apibara repo
https://github.com/apibara/dna/issues/361
