### ISSUE TITLE
[feat] Improve canvas zoom

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#44]
Have the canvas zoom use the cursor position to create a more intuitive and user-friendly zoom.

Currently, zooming in and out of the canvas just scales the canvas. This task is to set up the zoom to work in a way that makes it look like you are zooming into the portion of the canvas you are hovering with the mouse instead of uniformly scaling the canvas.

#### References
[Current canvas scaling logic](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/frontend/src/canvas/Canvas.js#L42)

**Comment by addegbenga** [comment]
i will like to work on this

**Comment by Joeysmart007** [comment]
I'll like to work on this
