### ISSUE TITLE
[feat] Load colors from backend

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#45]
Create a route on the backend, `getColors`, to get the canvas colors from Postgres. Then, use this route on the frontend to load the colors.

#### References
- [Backend routes](https://github.com/keep-starknet-strange/art-peace/tree/main/backend/routes)
- [Postgres table](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/postgres/init.sql#L67)
- [Frontend colors](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/frontend/src/canvas/Canvas.js#L28)

**Comment by Xaxxoo** [comment]
Hi, may I please take this ?
