### ISSUE TITLE
[feat] Prevent canvas re-init

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#47]
When initializing the canvas in Redis, add a check, which will return an error if the canvas element already exists. ( No re-initializing the canvas from the backend )

#### References
- [Canvas init function](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/backend/routes/canvas.go#L17)

**Comment by addegbenga** [comment]
I will love to work on this

**Comment by Ayoazeez26** [comment]
I would love to work on this!
