### ISSUE TITLE
[feat] Store template data into Postgres

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#48]
Add template image data ( `data` in Postgres ) and hash to Postgres through the backend. For now, other fields can be set to 0 or empty values.

#### References
- [Postgres table](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/postgres/init.sql#L87)
- [Backend path 1](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/backend/routes/templates.go#L72)
- [Backend path 2](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/backend/routes/templates.go#L91)

**Comment by Xaxxoo** [comment]
May I please take this and resolve it ?

**Comment by addegbenga** [comment]
I will love to work on this

**Comment by b-j-roberts** [comment]
@addegbenga and @Xaxxoo , I am going to start only allowing one issue at a time per person. So if you can complete your other issues and get them merged, I will assign you to these other issues.

**Comment by Dprof-in-tech** [comment]
hi @b-j-roberts 
please i would love this to be assigned to me

**Comment by b-j-roberts** [comment]
Awesome @Dprof-in-tech ! Welcome to the project. Let me know if you have any questions!

**Comment by Dprof-in-tech** [comment]
i sure will.

**Comment by Dprof-in-tech** [comment]
Hello @b-j-roberts , i'm so sorry but I won't be able to resolve this issue because I have so minimal a knowledge on Go. Please unassign me from this task, thank you

**Comment by b-j-roberts** [comment]
Alright @Dprof-in-tech , thanks for getting back to me and letting me know.

I'd be happy to help you with the Go side in Office hours, but understand if you'd rather drop the issue.
There will be more frontend tasks coming soon, would you like me to ping you then and you can try and take one?

**Comment by Dprof-in-tech** [comment]
I already have parts of the code that should fill it up written out.

We could complete it together, at least, I'd get more familiar with Go

**Comment by Joy-Adah** [comment]
Hi @b-j-roberts can I be assigned this?

**Comment by b-j-roberts** [comment]
I'll assign @ptisserand for now, if you'd like you can try and collaborate with @Dprof-in-tech . But no pressure there

@Dprof-in-tech & @Joy-Adah , I'll have more issues before next week. If you'd like to keep an eye out, you can also watch the project to get updates

**Comment by Dprof-in-tech** [comment]
That's okay Chief. Thanks for the heads up

**Comment by ptisserand** [comment]
Hi @b-j-roberts I'm wondering which value should we use for primary key?
Should the caller specify the primary key ?

**Comment by b-j-roberts** [comment]
@ptisserand

Things have changed with template images now, so it would probably be best to create a new table in the postgres `TemplateData`, which just tracks `hash` and `data` fields. Then this can be joined to the `Templates` table if/when needed.

**Comment by ptisserand** [comment]
> @ptisserand
> 
> Things have changed with template images now, so it would probably be best to create a new table in the postgres `TemplateData`, which just tracks `hash` and `data` fields. Then this can be joined to the `Templates` table if/when needed.

Do you mean a table like:
```sql
CREATE TABLE TemplateData {
  key integer NOT NULL PRIMARY KEY,
  hash text NOT NULL,
  data bytea NOT NULL,
};
```

And so `insert` will be done with [`addTemplateData`](https://github.com/keep-starknet-strange/art-peace/blob/211a1dd2e1b96b984459e5b606405a09712ac241/backend/routes/templates.go#L140) ?

**Comment by b-j-roberts** [comment]
@ptisserand Yes, that table looks good. You can make the key auto-incrementing too. There are auto-incrementing keys in init.sql you can find.

The insert will be done at both linked backend locations in the description.
