### ISSUE TITLE
[feat] getUsername backend route

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#49]
Add a route to the backend for `getUsername` to get a username from a user address in Postgres. Take the `address` as a query argument and return the username from Postgres.

#### References
- [User routes](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/user.go)
- [Postgres table](https://github.com/keep-starknet-strange/art-peace/blob/3795e979ab0852ae3f6cccddc308060862a2289b/postgres/init.sql#L30)

**Comment by manoahLinks** [comment]
can i hop on this

**Comment by b-j-roberts** [comment]
For sure @manoahLinks ! I'll assign you. Welcome to the project.

**Comment by manoahLinks** [comment]
thanks, on it
