### ISSUE TITLE
[feat] Backend pixel validation

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#5]
Add checks to all the pixel routes to validation `position` and `color` ( make sure they are in the correct range ) before using them.

#### References
- [pixel routes](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/pixel.go)
- [other relevant route](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/indexer.go)

**Comment by aweolumidedavid** [comment]
I'd like to work on this

**Comment by b-j-roberts** [comment]
Awesome, I'll assign you @aweolumidedavid . Welcome !

**Comment by b-j-roberts** [comment]
Hey @aweolumidedavid , are you actively working on this? I'd like to free it for someone to take if not. I'll be adding more issues in the future you can take if you haven't had time for this.
