### ISSUE TITLE
[feat] Websocket configs to backend config

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#6]
Add websocket upgrader configs, like `ReadBufferSize`, to the `backend.config.json`.

#### References
- [websocket setup](https://github.com/keep-starknet-strange/art-peace/blob/main/backend/routes/websocket.go)
- [config json](https://github.com/keep-starknet-strange/art-peace/blob/main/configs/backend.config.json)

**Comment by raizo07** [comment]
Hello @b-j-roberts I'll like to be assigned to work on this.
