### ISSUE TITLE
[feat] Hash template images

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#7]
Template images will store only their hash onchain. And only the pixel color values will be hashed, not the entire jpg.

The task is to use the Poseidon hash function to hash image pixel data, which can be replicated onchain.

Implement the `hashTemplateImage` function to take an `[]byte` that contains an array of color values (color value == color index in colors array). Then use Poseidon hash to get the same hash that the same `Array<u8>` would give on Starknet.

Note: Treat transparent pixels as a 0xFF byte.

**Related Issues:** https://github.com/keep-starknet-strange/art-peace/issues/8

There are 2 options here, the preferred option is to use a Go `Poseidon` hash library and make sure the output matches the onchain Poseidon hash value.
The other option is to create a templateHash function on the ArtPeace contract, which takes a `Span<u8>`, then use a bash script/sncast to call the contract from the backend.

#### References
[Go library 1](https://github.com/triplewz/poseidon)
[Go library 2](https://pkg.go.dev/github.com/iden3/go-iden3-crypto/poseidon)
[Cairo Poseidon hash](https://book.cairo-lang.org/ch11-05-hash.html?highlight=hash#working-with-hashes)
[Code segment](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/backend/routes/templates.go#L25)

**Comment by tekkac** [comment]
Ahoy, could I try this one? Are you open to use the  [poseidon lib from Nethermind](https://github.com/NethermindEth/juno/blob/main/core/crypto/poseidon_hash.go)

**Comment by b-j-roberts** [comment]
Yo, welcome to the project @tekkac .
Yeah, that would be fine. I just linked to the ones I saw online.
