### ISSUE TITLE
[feat] Last placed time tracker

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#70]
Users can only place pixels every X minutes. Most of the logic for this is setup on the frontend, however, we want to load the last time a user placed a pixel from Postgres.

This issue is to create a backend route for getting the last time placed from postgres, which takes a user address as a query parameter. Then, use that route on the frontend to load the last time a pixel was placed by the user.

#### References
- [Useful backend route example](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L31)
- [Frontend fetch location/variable](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/canvas/PixelSelector.js#L8)
- [Useful frontend fetch example](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/canvas/PixelSelector.js#L25)
- [Postgres table](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/postgres/init.sql#L16)

**Comment by CollinsC1O** [comment]
Hi @b-j-roberts can I work on this

**Comment by b-j-roberts** [comment]
Yeah! I'll assign you now @CollinsC1O . Welcome to the project, and let me know if you have any questions.

**Comment by CollinsC1O** [comment]
Okay.
Thank you @b-j-roberts
