### ISSUE TITLE
[feat] Load Extra Pixels on frontend

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#71]
Users can get extra pixels ontop of the one every X minutes. Most of the logic is setup on the frontend, but we need to load the number of extra pixels a user has on the frontend.

This issue is to make a fetch request to the backend to get the number of extra pixels a user has.

#### References
- [Backend route to query](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L11)
- [Frontend variable to update on fetch](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/App.js#L53)
- [Useful frontend fetch example](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/canvas/PixelSelector.js#L25)

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by b-j-roberts** [comment]
For sure, thank you!

**Comment by Ayoazeez26** [comment]
@b-j-roberts how do I bypass this CORS error I'm getting while trying to fetch
![image](https://github.com/keep-starknet-strange/art-peace/assets/44169294/6cc85dc8-9fe4-41fb-8dc6-fdccdff0d233)

**Comment by Ayoazeez26** [comment]
I saw a comment you made on #72 , I would use that temporary fix
