### ISSUE TITLE
[feat] Load username on frontend

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#72]
Users can create usernames within the accounts tab. We need to load their saved username from the backend.

This issue is to make a fetch request to the backend to get the username.

#### References
- [Backend route to query](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L31)
- [Frontend variable to update on fetch](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/tabs/Account.js#L7)
- [Also set this to saved](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/tabs/Account.js#L10)
- [Useful frontend fetch example](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/canvas/PixelSelector.js#L25)

**Comment by fishonamos** [comment]
I will love to work on it. @b-j-roberts .

**Comment by abdulqaharu** [comment]
I will like to work on this

**Comment by b-j-roberts** [comment]
Cool, I'll assign you! Welcome to the project. Please let me know if you have any questions!

**Comment by abdulqaharu** [comment]
Thank you, sure I'll.

**Comment by abdulqaharu** [comment]
I have been getting internal server error while trying to fetch the username from /getUsername route, @b-j-roberts . Any pointers as to why this is happening?

**Comment by b-j-roberts** [comment]
@abdulqaharu yeah, cors can be annoying and confusing.

Since there are no rows in the `Users` table `getUsername` is returning an error on the backend here : https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L37

I'd recommend either moving the [access control setup](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L42) to the beginning of the `getUsername` function on the backend. Or treat an error as no username received on the frontend.

**Comment by abdulqaharu** [comment]
Alright, but then, I can see a set username [form](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/tabs/Account.js#L53) in the frontend that has no api call attached to it. Wont that mean that a username needs to be set first before the [getUsername](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L31) function can retrieve it?

It is something I can fix if that is the case.

**Comment by abdulqaharu** [comment]
> @abdulqaharu yeah, cors can be annoying and confusing.
> 
> Since there are no rows in the `Users` table `getUsername` is returning an error on the backend here :
> 
> https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L37
> 
> I'd recommend either moving the [access control setup](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L42) to the beginning of the `getUsername` function on the backend. Or treat an error as no username received on the frontend.

Fixed. So I just used a window.alert in the frontend to notify the user when there is no username retrieved set yet or is there a notification component for this purpose. @b-j-roberts

**Comment by b-j-roberts** [comment]
> Fixed. So I just used a `window.alert` in the frontend to notify the user when there is no username retrieved yet or is there a notification component for this purpose. Time to raise a PR for this issue, yes? @b-j-roberts

I'd prefer no alert. No username being retrieved should just mean that `isUsernameSaved` should be set to false. So the form will be there for a username to be created.
