### ISSUE TITLE
[feat] User pixels placed

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#73]
As part of the accounts tab, we would like to track the total number of pixels a user has placed. This data can be queried from postgres `Pixels` table by checking the count of pixels from a users `address`.

This issue is to create a backend route for getting the amount of pixels placed from postgres, which takes a user address as a query parameter. Then, use that route on the frontend to load the number of pixels placed.

#### References
- [Useful backend route example](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L31)
- [Frontend fetch location/variable](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/tabs/Account.js#L8)
- [Useful frontend fetch example](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/frontend/src/canvas/PixelSelector.js#L25)
- [Postgres table](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/postgres/init.sql#L4)

**Comment by fishonamos** [comment]
Hi @b-j-roberts I will love to work on this.

**Comment by b-j-roberts** [comment]
Awesome, assigning you now!
