### ISSUE TITLE
[feat] NFT likes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#74]
Users can mint NFTs off of the canvas. It would be cool if users could like NFT images.

This issue is to create the "Like" functionality on the backend. This includes adding a table to track likes, something like :
```
CREATE TABLE NFTLikes (
    nft_key integer NOT NULL,
    liker char(64) NOT NULL
)
```
with indexes on both parameters.

Then create 2 backend routes for liking & unliking an NFT, which will take the NFT key and user address as json objects in the body. Then either add/remove rows from the NFTLikes section.

Lastly create another route to get the number of likes for a specific NFT, which takes the nft key as query parameters and returns the COUNT of likers for that key.

#### References
- [Useful backend get route example](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/user.go#L31)
- [Useful backend post route](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/colors.go#L98)
- [Useful backend set postgres command](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/indexer.go#L144)
- [NFT Postgres table](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/postgres/init.sql#L118)

**Comment by mubarak23** [comment]
@b-j-roberts i will like work on this. kindly assign this issue to me

**Comment by b-j-roberts** [comment]
Sure, I can assign you. Thanks!

**Comment by mubarak23** [comment]
if both NFT key and user address are passed as query parameters, then our POST route for both NFTLikes and UnNFTLikes will be empty request body

i know we can do this.

but won't it be better if we pass both NFT key and user address in the body of the POST Request @b-j-roberts what do you think

**Comment by mubarak23** [comment]
then for our like counts for a specific NFT, we can pass the NFT Key as route parameters in the GET Request  @b-j-roberts

**Comment by b-j-roberts** [comment]
> but won't it be better if we pass both NFT key and user address in the body of the POST Request @b-j-roberts what do you think

Yes, it is better to pass them in the body. "Query parameters" was a mistake in my description, I accidentally mixed up the request types.

NFT liking POST requests should use the body and the get Likes request should use query/route parameters

**Comment by MubarakCinderbuild** [comment]
am getting the following error when i ran docker compose up  `services.deployer.restart must be a string` can i ran the project with docker @b-j-roberts

**Comment by mubarak23** [comment]
i keep getting this error with my docker postgres DB everytime i ran docker compose up 
 ```

postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  | 
postgres-1  | 2024-04-24 20:00:57.378 UTC [1] LOG:  starting PostgreSQL 14.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres-1  | 2024-04-24 20:00:57.378 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2024-04-24 20:00:57.379 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1  | 2024-04-24 20:00:57.401 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2024-04-24 20:00:57.424 UTC [21] LOG:  database system was shut down at 2024-04-24 19:45:55 UTC
postgres-1  | 2024-04-24 20:00:57.457 UTC [1] LOG:  database system is ready to accept connections
```

@b-j-roberts 
what could be the reason why it is shutting down unexpectedly

**Comment by mubarak23** [comment]
@b-j-roberts i was able to fix it, its had issue with my new table, NOT NULL issue, when i fixed the SQL Schema issue and ran, 
`docker-compose down --volumes `

everything was fixed after it.

A PR is available for review .

**Comment by mubarak23** [comment]
Can you close this issue since the PR was merged @b-j-roberts
