### ISSUE TITLE
[feat] Read username on getPixelInfo

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#75]
When clicking a pixel on the canvas, you can see who placed that pixel. This is done by querying the backend `getPixelInfo` function.

This issue is to add usernames to the `getPixelInfo` query, by first getting the user address that placed the pixel ( already done ), then using that address to check if the user has a username stored in postgres.

If there is a username, return the username. Otherwise, return the address as it is now.

#### References
- [getPixelInfo](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/pixel.go#L46)
- [Username postgres table](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/postgres/init.sql#L30)

**Comment by princeibs** [comment]
Can I hop on this? @b-j-roberts

**Comment by b-j-roberts** [comment]
For sure @princeibs . Welcome to the project!
