### ISSUE TITLE
[feat] Day tracker

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#76]
There will be different quests and votes for each day.

This issue is to create a backend route to get the current day start time. We store the day's data in Postgres. You'll need to query the Postgres SQL Days table to get the `dayStart` on the highest `dayIndex` and return it. ( assume there is always at least one value in the days table )

#### References
- [Days table in postgres](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/postgres/init.sql#L36)
- [Example backend route](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/colors.go#L62)

**Comment by Pycomet** [comment]
Hey @b-j-roberts, can I work on this 🙂?

**Comment by b-j-roberts** [comment]
Definitely @Pycomet , welcome to the project!
