### ISSUE TITLE
[feat] Get todays quests route

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#77]
Each day will have different daily quests.

This issue is to create a backend route to query all the quests of the current day index. Try and do this in a single Postgres SQL query to prevent back and forth with the server.

You will get the `dayIndex` from the `Days` table ( the current day index is the largest `dayIndex` stored ). Then use that day index to limit the returned quests from the `DailyQuests` table.

#### References
- [Days table](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/postgres/init.sql#L36)
- [DailyQuests table](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/postgres/init.sql#L44)
- [Useful example backend route](https://github.com/keep-starknet-strange/art-peace/blob/2dc9e5bd1240a4246317dc214d3c24e745b272d8/backend/routes/quests.go#L27)

**Comment by kateberryd** [comment]
Hi

**Comment by b-j-roberts** [comment]
Cool, I'll assign you @kateberryd . Welcome to the project!

**Comment by kateberryd** [comment]
Thank you
