### ISSUE TITLE
[feat] png data -> pixel data

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#8]
Convert a given png image to pixel data using approximation. Loop through each pixel in the png image, approximate which color in our `colors` array it is closest to, and then add the corresponding color's index into the returned `[]byte` of pixel data.

**Related Issues:** https://github.com/keep-starknet-strange/art-peace/issues/7

#### References
- [Code Section](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/backend/routes/templates.go#L31)

**Comment by thomas192** [comment]
Hey, can I take this one ?

**Comment by b-j-roberts** [comment]
Definitely, happy to have you on the project @thomas192 !

**Comment by b-j-roberts** [comment]
Quick note @thomas192 : sorry if the issue description led you astray already, but I believe we will just support PNG images for now, since we want to allow transparent pixels.
Encode any transparent pixel as a 0xFF pixel color. Let me know if you have any questions.

**Comment by Gift-Naomi** [comment]
@b-j-roberts please assign me to work on this.
