### ISSUE TITLE
[feat]  Create Cors Function in Routes

### ISSUE THREAD

**Issue by fishonamos** [keep-starknet-strange/art-peace#82]
I think we should Implement a function to enable Cross-Origin Resource Sharing (CORS) for route handlers. This function will set the necessary CORS headers in the response to allow cross-origin requests. When we call this function after processing each route handler, we ensure consistent CORS behavior across the application.

Example: 

```
func EnableCORS(w http.ResponseWriter) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
}

func ExampleRouteHandler(w http.ResponseWriter, r *http.Request) {
	//handler implementation

	// Call EnableCORS after the request
	EnableCORS(w)
}
```

What do you think about this @b-j-roberts?

**Comment by Dprof-in-tech** [comment]
hello @fishonamos , i'm Isaac a fullstack Javascript dev. I would love to take this task

**Comment by b-j-roberts** [comment]
I agree @fishonamos , did you want to work on this? If not I can assign @Dprof-in-tech .

**Comment by fishonamos** [comment]
Yes @b-j-roberts. I will work on it.

**Comment by b-j-roberts** [comment]
Hey @fishonamos , I did part of this as part of my refactor PR I merged yesterday because I was making things consistent.

The main thing I would like changed here still is importing the access control values from `backend.config.json`, if you would like to do that.

[New heading control function](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/backend/routes/responses.go#L5)

**Comment by fishonamos** [comment]
Hi @b-j-roberts . Please check this out. I also added dynamic methods call. For example, for GET only requests, we will call 	`SetupHeaders(w, "GET")`


https://github.com/fishonamos/art-peace/tree/cors

**Comment by b-j-roberts** [comment]
> Hi @b-j-roberts . Please check this out. I also added dynamic methods call. For example, for GET only requests, we will call `SetupHeaders(w, "GET")`
> 
> https://github.com/fishonamos/art-peace/tree/cors

I don't think we want to have different methods allowed for each request. Since we are always allowing "GET, POST, ..." from the specified origin.

**Comment by fishonamos** [comment]
Ok. I will change that.
