### ISSUE TITLE
[feat] Limit received image proportions

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#9]
For the `addTemplatePng` route, limit the proportions to be between `5x5` and `50x50` for template images. Make sure to return a relevant message if the limits were broken & exit.

#### References
[Code section](https://github.com/keep-starknet-strange/art-peace/blob/f62a06ef0fcea5a810a9d380d974f7106c76b56a/backend/routes/templates.go#L37)

**Comment by thomas192** [comment]
May I take this one too ? :)

**Comment by b-j-roberts** [comment]
For sure @thomas192 !
