### ISSUE TITLE
[feat] Keep track of block & indexer cursor

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#93]
As blocks are processed by our Apibara indexer, they will update Postgres and Redis through our backend. However, if the indexer restarts/crashes, it will start re-indexing blocks from block 0 and thus will reprocess all that has happened.

This issue is to keep a persistent cursor so restarts always start from the last processed position. You can do this using the `PERSIST_TO_REDIS` environment variable on the indexer.

#### References
- [Apibara persistent storage docs](https://www.apibara.com/docs/indexers/persistence#persisting-state)
- [Indexer setup](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/docker-compose.yml#L79)
- [Redis URL](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/configs/docker-database.config.json#L2)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @Jemiiah

This issue might be kinda complex, so let me know if you're still interested here.

**Comment by Jemiiah** [comment]
Thank you I will take the task @b-j-roberts

**Comment by BillXJ** [comment]
Pls can I have this task @b-j-roberts

**Comment by Jemiiah** [comment]
I’m still working on this almost done
