### ISSUE TITLE
[feat] Place extra pixels devnet position formatting

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#94]
Currently, the place extra pixels devnet function takes 3 args on the backend, `x`, `y`, and `color`.
This issue is to change that to use `position` and `color` instead.

This includes changing the backend devnet function and the frontend call.

#### References
- [Related issue for place pixels](https://github.com/keep-starknet-strange/art-peace/issues/4)
- [Backend function](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/backend/routes/pixel.go#L117)
- [Frontend call](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/canvas/ExtraPixelsPanel.js#L21)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @GoSTEAN

Please comment here so I can assign you, if you're still interested.

**Comment by GoSTEAN** [comment]
@b-j-roberts  I am interested

**Comment by aweolumidedavid** [comment]
I am sorry for commenting, I did not know that interest has already been indicated. I didn't mean to be rude.

**Comment by b-j-roberts** [comment]
@aweolumidedavid No worries at all; a lot of people come to show interest in issues during office hours this morning.

I'll be adding more issues that haven't been volunteered for yet today as well.
