### ISSUE TITLE
[feat] Color voting user interaction

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#95]
This issue contains 2 parts : 

1. Create a backend route, `vote-color-devnet,` which will call a script to vote for a color on starknet devnet. Please create the script and set it up. Note: The onchain part is not set up yet; for now, just have it call a non-existing `vote_color` function on starknet.
2. Add functionality on the frontend to call the `vote-color-devnet` route when clicking on a color to vote on.

#### References
- [Example devnet route func](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/backend/routes/nft.go#L76)
- [Frontend vote location](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/voting/Voting.js#L10)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @fishonamos 

Please comment here so I can assign you, if you're still interested.

**Comment by fishonamos** [comment]
Hi @b-j-roberts . Ready to begin!
