### ISSUE TITLE
[feat] Quests description links formatting

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#96]
Currently, quest descriptions are completely static text.

This issue is to allow encoding links in the quest description of the format `[link example](http://link-endpoint.com)`. So when displaying the quest description, links will be appropriately displayed and clickable to link to other locations.

#### References
- [Frontend quest descriptions](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/quests/QuestItem.js#L78)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @addegbenga 

Please comment here so I can assign you, if you're still interested.

**Comment by addegbenga** [comment]
Ready to work on this.
