### ISSUE TITLE
[feat] Animate tabs openning

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#97]
When clicking a tab, displaying pixel info, or extra pixels panel. The tab on the right-hand side just spawns in.

It would be cool to animate the tab to come in/leave on the right side of the screen when opening/closing.

#### References
- [Tabs to animate in](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/TabPanel.js)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @Ayoazeez26 

Please comment here so I can assign you, if you're still interested.

**Comment by Ayoazeez26** [comment]
@b-j-roberts thanks, I am still interested
