### ISSUE TITLE
[feat] Quests form animation

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#98]
When opening a quest claim form, everything opens immediately. It would be cool to animate for form entry and exit by expanding down/up on open/close.

#### References
- [Quest form](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/quests/QuestItem.js#L99)

**Comment by b-j-roberts** [comment]
Thanks for volunteering for this issue @oshioke-salaki

Please comment here so I can assign you, if you're still interested.

**Comment by Oshioke-Salaki** [comment]
Yes I am interested
