### ISSUE TITLE
[feat] Quests address hex checker

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/art-peace#99]
This issue is to create functionality on the quest's input validator to ensure that addresses match the correct format.

Please create a check to ensure the address is in hex format.

#### References
- [Address checker logic](https://github.com/keep-starknet-strange/art-peace/blob/4ba50984e8a0bfcfeae5b3eb9f90f4307300d427/frontend/src/tabs/quests/QuestItem.js#L45)

**Comment by Calebux** [comment]
I'm interested
